### ISSUE TITLE
Bitwarden On-premises Hosting - E-mail not send

### ISSUE THREAD

**Issue by danieltaqueto** [bitwarden/server#1021]
Hello!

(First of all, sorry for my english. I'm not fluent but I'm learning)

I have recently know about bitwarden and had adopted as my personal password vault. Now I'm trying to implement in my organization, but I'm not getting done the e-mail configuration. We use a external server with CPanel. This server is used for various another SMTP services already running, such as GLPI, Zabbix, Veritas...

My configuration file (./bwdata/env/global.override.env) is currently like this:

globalSettings__mail__replyToEmail=no-reply@MYDOMAIN.COM
globalSettings__mail__smtp__host=MYDOMAIN
globalSettings__mail__smtp__port=465
globalSettings__mail__smtp__ssl=true
globalSettings__mail__smtp__username=EMAIL@MYDOMAIN.COM
globalSettings__mail__smtp__password=PASSWORD

Have tried also with no SSL with the port 587.

In this lask week I've spended many hours reserching about this problem and found many posts like this, but neither sollution work out for me.

I almost have no knoledge in Docker, so if any of you could help me would be very kind.

Thank you!

**Comment by Kuchenm0nster** [comment]
hi there, try smtp port 587 and ssl=true
sadly smtp is kind of confusing regarding SSL, STARTLS and the different ports that are available. Compare https://www.mailgun.com/blog/which-smtp-port-understanding-ports-25-465-587/

**Comment by Hinton** [comment]
Thanks for getting in touch! We use GitHub issues as a place to track bugs and other development related issues. If you'd like help using or configuring Bitwarden, please contact our Customer Success team here: https://bitwarden.com/contact. You can include a link to this issue in the message content. You can also search for an answer in our [help documentation](https://bitwarden.com/help/) or get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/). The issue here will be closed.
