### ISSUE TITLE
TOTP Access Control Enhancements

### ISSUE THREAD

**Issue by haneef95** [bitwarden/server#1069]
Hi,

When sharing an item/collection, the TOTP key/seed is shared with it, which the user could copy and use on another app without access logs.

It would be good if there is an option to only allow users to get the expiring OTP code without giving them access to the key/seed.

Possibly the seed is kept on the server and the OTP code is computed/calculated on the server, and is only sent to the user upon request?

And with each TOTP request being logged?

Thanks,

**Comment by tgreer-bw** [comment]
If you enable "hide passwords" the seed and any hidden fields are not displayed to the users/groups.

**Comment by clayadams5226** [comment]
Looks like @tgreer-bw was about to get you the information you needed. However, if you'd like to request something different you should signup for our community forum. 

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by MarkAlicz** [comment]
Remove
