### ISSUE TITLE
Enhancement: Zero Trust Private Network Access Support

### ISSUE THREAD

**Issue by haneef95** [bitwarden/server#1070]
Hi,

It would be very good from a security standpoint to support the use of these types of services, example includes:
- [Cloudflare Access](https://www.cloudflare.com/en-gb/teams/access/)
- [ZScaler Private Access](https://www.zscaler.com/products/zscaler-private-access)
- [Azure Active Directory Application Proxy](https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/application-proxy) — included at no additional cost in AAD P1 licence.

# Benefits
Some of the benefits of these products include:
- Application firewall with authentication.
- Bot/Crawler protection for the origin/bitwarden server.
- Attackers would've to pass through robust security even before sending/receiving a byte from the origin/bitwarden server, let alone attempting to login or register.
- No need to expose Inbound ports on the origin/Bitwarden server.
- For legitimate users, it should just be a single additional click to authenticate with their SSO IdP, which they'll be doing in Bitwarden as well anyway.
- Mostly no additional cost for the users/businesses. Small entities could use Cloudflare Access for free. Large entities most likely already have at least one of the above products.
- None of the above services are known to charge for bandwidth

These products are used by small entities and corporations alike. Especially given that Cloudflare Access is currently free for 50 users, and AADAP is included in P1 licenses.

# Potential solution
The above services should already work well with Bitwarden Web Vault.

However, the other Bitwarden client applications would need to be modified to facilitate such services.

- The client applications might have to add support for web-based authentication as opposed to what currently seems to be form-based authentication only, 
- or OAuth 2.0 authentication support.

**Comment by Greenderella** [comment]
Hi @haneef95 

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

**Comment by haneef95** [comment]
Added: https://community.bitwarden.com/t/enhancement-zero-trust-private-network-access-support/16443

**Comment by cscharf** [comment]
thanks @haneef95 , closing this issue on Github now.
