### ISSUE TITLE
How to change database recovery mode to simple to prevent growing sql transaction logs?

### ISSUE THREAD

**Issue by Starbase12** [bitwarden/server#1086]
If I understood correctly tha ldf-files are sql-transaction logs. As soon as there is no fully working backup routine in the background, the transaction log will will get bigger and bigger. Is there a way to permanently change the "database recovery mode" to "SIMPLE" for my bitwarden instance?

_Originally posted by @Starbase12 in https://github.com/bitwarden/server/issues/648#issuecomment-760430191_

**Comment by clayadams5226** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk
