### ISSUE TITLE
SSO button on login page displayed for no reason

### ISSUE THREAD

**Issue by sderungs** [bitwarden/server#1105]
Bitwarden server version: 1.39.0
Bitwarden web version: 2.18.0

"Enterprise Single-Sign-On" button is shown on login page even though no organization in our deployment has SSO configured.
This button should not be visible in this case as it only confuses users and we consider it a bug.

**Comment by clayadams5226** [comment]
This is currently the expected behavior. 

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by Mart124** [comment]
I would also tend to say that this button should be hidden if no SSO is configured at all, so current behavior more or less seems like a bug.
I'm here because I'm also looking to have it hidden if not needed, making things more user-friendly...
Is this perhaps already in your backlog @cscharf ?
Many thanks 👍

**Comment by cscharf** [comment]
It's not currently on the backlog @Mart124 , however if it's not already on the community forum I would highly suggest getting a topic opened there for it. Trey does monitor those and advocates for community requests during roadmap and priority discussions. I personally like to have as many buttons as possible on every screen, same with my car dashboard and interpersonal relationships, the more buttons to push the better.... 😁  (just kidding, I understand the desire to have it hidden, but that takes some configuration changes, client updates and "real" work to do and do it well, ensuring enterprise user onboarding is also smooth, etc.)

**Comment by Mart124** [comment]
Just for completeness, I found the corresponding request on the community :
https://community.bitwarden.com/t/toggle-to-hide-new-sso-login-button/14381

@cscharf, thank you again for your detailed feedback, as usual, really appreciated 👍
