### ISSUE TITLE
Misleading Change Email Language?

### ISSUE THREAD

**Issue by devmattrick** [bitwarden/server#1145]
In the change email, it has the following at the end:
> If you did not try to change an email address, you can safely ignore this email.

I think if a party other than the user has access to the user's web vault it should ideally have the same language at the end of the new logged in device email:
> You can deauthorize all devices that have access to your account from the web vault under Settings &rarr; My Account &rarr; Deauthorize Sessions.

Or, even better something like:
> If you did not try to change an email address, protect your account by deauthorizing all devices that have access to your account from the web vault under Settings &rarr; My Account &rarr; Deauthorize Sessions.

Thanks!

**Comment by clayadams5226** [comment]
Hey @devmattrick, thanks for bringing this up. We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
