### ISSUE TITLE
Error while importing from Lastpass: "This organization can only have a maximum of 2 collections"

### ISSUE THREAD

**Issue by kunalgrover05** [bitwarden/server#1152]
I was trying to migrate my data from LastPass -> Bitwarden Free tier, and I got an error: "This organization can only have a maximum of 2 collections". 

I found the issue to be very non-descriptive about what is going on, and couldn't find anything on searching about it. The reason for that was LastPass exports the content including a "grouping" field which they determine as the most reasonable bucket for the website, eg: Email / Education etc. This leads to multiple organizations being created which causes the error and stops an import. 

Workaround: Simply delete the grouping column and the data will get imported. 

Ask: It should be clear what the error means and a workaround should be present in the onboarding help section: https://bitwarden.com/help/article/import-from-lastpass/

**Comment by tgreer-bw** [comment]
@fschillingeriv - this and the field text limits would be good to add I think.

**Comment by tgreer-bw** [comment]
Issue moved to [bitwarden/help #408](https://github.com/bitwarden/help/issues/408) via [**ZenHub**](https://www.zenhub.com/)

**Comment by bsbell21** [comment]
I still go this error today 05/11/21 importing from LastPass so don't think it'd been resolved

**Comment by stratocentric** [comment]
I had this error as well.. it seems like a way for lastpass to make it hard to leave.  Lastpass is total garbage now... will bitwarden make it easy to transfer?  Or is there another solution that will?

**Comment by tgreer-bw** [comment]
Hi @stratocentric! Here's a note on how to address it:
https://bitwarden.com/help/article/import-from-lastpass/#maximum-collections-error

**Comment by jabielecki** [comment]
Alternative solution, more clickable, is to go back to the LastPass Vault and put all the passwords into a single folder, by using `Actions -> Move To Folder` on multiple selected passwords. Then remove the csv and restart the whole import procedure from scratch.

I've used folder "(none)" which was already my biggest one.

The LastPass folder is called `grouping` inside the LastPass csv.

Pay attention whether you are importing to an organization or to your own account, in most cases you want the latter.

**Comment by epyu-lee** [comment]
This is still an actual issue.  It only arises when importing to an Organization, not to a user Vault.  A problematic workaround is available.  Importing to a user vault imports the Lastpass categories as folders, rather than as collections; which makes perfect sense.  The entries may then be bulk transferred to an Organization.  This benefits from having an empty user.  Which current users compliant with BitWarden's terms of service are not permitted.  The dependent interpretation of LastPass category depending on import path could do with improvement.  The unnecessary limitation comes up in product reviews.

The second-class status of folders within organizations is a subject for another day.
