### ISSUE TITLE
The Authorization header causes conflicts with page passwords configured via web engine

### ISSUE THREAD

**Issue by ThePineapple27** [bitwarden/server#1161]
Hello,

I'm trying to set up a self-hosted Bitwarden instance that is protected by a page password. I'm using nginx's auth_basic to accomplish this. The image below is what I've done. I made sure that the API isn't guarded by this as not to mess up anything that isn't a web browser (extensions, apps, etc).

![image](https://user-images.githubusercontent.com/35678457/109075448-c2438200-76be-11eb-9e89-365541965d6a.png)

The reason this password is useful despite the login screen already in place is that it can allow for a quick whitelist to the page without having to worry about IP addresses or creating a VPN while still making it difficult for outsiders to know what you're hosting so they're less likely to attack it (for example, by sending phishing emails).

Passwords like this use the Authorization header.

![image](https://user-images.githubusercontent.com/35678457/109075620-059df080-76bf-11eb-8144-61e590db82aa.png)

Unfortunately, it seems like Bitwarden also uses this header. This creates a conflict where when this password is in use, users can't log into their vault.

My suggestion to fix this is to simply use a different header name. Apart from that, I'll use an IP-based whitelist for now.

Thank you!

**Comment by djsmith85** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
