### ISSUE TITLE
[Feature Request] Register Without Email

### ISSUE THREAD

**Issue by trymeouteh** [bitwarden/server#1185]
Please add an option to register without an email address and as an alternative you can register with an username and password. Of course by doing this option it should warn you that there is no account recovery if you forget your username or password. And username accounts should not allow any automatic renewal on payments.

I would like to use an open source cloud storage password manager but I cannot find one that will have email as optional. VPN providers like Mullvad and IVPN allow for registration without an email.

**Comment by shhlkien** [comment]
By signing up without email you put sensitive informations on your own in dangerous area and the server can't manage if you create thousands of accounts to try the premium feature for free, which is a disadvantage to both side, nobody wants that

**Comment by trymeouteh** [comment]
My angle was to not have your email tied to the account for privacy but you do mention a good point on people abusing the service. I would like to suggest the this.

When signing up for an non-email account, you will have to pay a one-time fee which will reduce people making hundreds of accounts or to continue trying the premium features for free.

**Comment by clayadams5226** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by trymeouteh** [comment]
https://community.bitwarden.com/t/register-without-email/26945
