### ISSUE TITLE
What's the purpose of Verify email ?

### ISSUE THREAD

**Issue by Mart124** [bitwarden/server#1187]
Hi,

More or less related to #640, but, what's the exact purpose of _Verify email_ ?

![image](https://user-images.githubusercontent.com/37041094/110138224-07a83380-7dd2-11eb-97c7-979e02728586.png)

Notification says :
_Verify your account's email address to unlock access to all features._

But I was not able to find missing features with an unverified account.

Could you tell us more ?

Many thanks 👍

**Comment by clayadams5226** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.

**Comment by edermi** [comment]
I think this is something that is worth discussing publicly, especially in organizational contexts this makes no obvious sense. I understand you're trying to keep noise on the Github issue tracker low, but there's quite some confusion regarding this behavior along many people I talked about it. In our organization, people don't do this because they do not understand the purpose (which is funny, because I as admin do not understand it either) and it is extra work for them. On my side, I have tons of "unverified" accounts and I'm not sure when this is going to blow up. 

So please, at least clarify the purpose and impact of the behavior in public or allow (at least orgs) to disable it.

**Comment by Mart124** [comment]
Same situation here :)
Some technical clarification would then be nice @clayadams5226 @kspearrin @cscharf 😉
Many thanks again 👍

**Comment by Mart124** [comment]
**Support :**
The main purpose to encourage user to verify their email is to avoid problems due to typos introduced during the registration. Processes like updating an account's email address (https://bitwarden.com/help/article/product-faqs/#q-how-do-i-change-my-email-address), activating an email as a 2FA method (https://bitwarden.com/help/article/setup-two-step-login-email/) and others require for users to check on their inbox for a confirmation code or activation link, if the email was introduced with a typo it's not possible to complete this actions and the account must be basically deleted and started from scratch with a new import.

**Me :**
Thank you very much for your reply, really appreciated !
I'm however not sure to really understand the benefit from verifying the configured email address, as per your examples.
When updating an account's email address, a verification code is sent to the new email address, not to the current one.
And when activating an email as a 2FA method, user is asked to set the address to receive codes to.
There's then no relation with the current email address.
Let's think about a on-premise installation, where self-registrations have been disabled (globalSettings__disableUserRegistration=true).
A user has been invited to join an organization.
He then clicks on the link in the email he received, and creates his account.
There's then no reason here to ask for email verification ; it's already verified, as he received the email to create his account.
Could we then simplify the process in this case, automatically setting the email as verified here ?
That would make sense.

**Support :**
I will forward this to our dev team for their review and consideration.

**Me :**
Thank you very much, let's then stay tuned !

**Comment by cscharf** [comment]
Our customer success team has added a card on our backlog for this, thanks @Mart124 and @edermi. Will consider this as we look at other product priorities.
