### ISSUE TITLE
Import from LastPass CSV fails to import text on Note when followed by carriage return

### ISSUE THREAD

**Issue by cmak3000** [bitwarden/server#1197]
The string of text following "Note:" on the below example does not get imported. All previous info gets imported correctly.

Example from credit card import (Column D "extra") in CSV:

**Imports incorrectly**
NoteType:Credit Card
Language:en-US
Name on Card:
Type:
Number: 1234567890
Security Code:123
Start Date:,
Expiration Date:January,2123
Notes:
1234

Imports correctly if last line is:
Notes:1234

**Comment by djsmith85** [comment]
Hi  @cmak3000 I've just had a look at the lastpassCsvImporter (bitwarden/jslib) and the accompanying tests. I've also added your example data to a separate test to verify that the import of the notes work.

Where did you try to import the above or similar CSV-file?

Are you self-hosting? Is it up to date?

Please let me know, and I'll have another look into it.

**Comment by cmak3000** [comment]
Hi Daniel.
I'm just a user and not a developer. Please let me know if this issue was filed in the wrong place.

I used the website import tool. Not a local instance of Bitwarden.

**Comment by djsmith85** [comment]
Hey @cmak3000 no worries about not being a developer. Tracking the issue here is fine, I just wanted to clarify that it wasn't a outdated local instance.

I've tried several approaches importing your example via the vault.bitwarden.com website. Unfortunately I haven't been able to reproduce the problem. The attached screenshot has all data including the notes field with a carriage return/newline chararacter.

![image](https://user-images.githubusercontent.com/2670567/111013836-470deb80-83a1-11eb-962f-eaa11d9990a6.png)

Would you be able to provide a redacted version of the initial file you tried to import? Possibly without touching the notes field.

Thanks in advance

**Comment by cmak3000** [comment]
Hi Daniel,
I've been able to reproduce the error with this redacted file.

Let me know if that works for you and thanks.

-Christian

**Comment by cmak3000** [comment]
Here is the file.

[git_test.zip](https://github.com/bitwarden/server/files/6143554/git_test.zip)

**Comment by djsmith85** [comment]
@cmak3000 Thank you very much for trying it again and providing a file. I've been able to reproduce the problem with the example. I'll have another look at it over the next couple of days.
