### ISSUE TITLE
Sensitive Information Should Be Hidden By Default

### ISSUE THREAD

**Issue by FreeWillyB** [bitwarden/server#1211]
As is, passwords are hidden when you view the login info pages. However, under identities, sensitive PII is such as social security numbers are NOT hidden. Furthermore, credit card numbers are also not hidden, but the 3 digit code IS hidden. All these items should be hidden by default.

**Comment by kendratodd** [comment]
Hi @FreeWillyB! We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) or enhancements like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
