### ISSUE TITLE
Uploading license results in 'invalid license'

### ISSUE THREAD

**Issue by paradoxicalNL** [bitwarden/server#1256]
Running the latest available version.

Exported the license from the vault.
Trying to import on my on premise machine, and gives me error:  'Er is een fout opgetreden: invalid license.'

**Version info:**
Status: Image is up to date for bitwarden/setup:1.40.0
docker.io/bitwarden/setup:1.40.0

**Comment by Greenderella** [comment]
Hi @paradoxicalNL 

You will want to make sure you are running the latest version of the server. If you are not using the latest version, you will want to update your server. Before you perform an update, please make sure you have a backup, clone or full copy of the bwdata directory. Once you are ready to update, you can follow the update procedure here:
https://bitwarden.com/help/article/updating-on-premise

Once you have updated your server, you will want to log into the Web Vault (https://vault.bitwarden.com) and go to Settings > Organizations > {YOUR ORG NAME} > Settings sub-tab (Gears Icon) > Subscription. There you will be able to download your new license file. You will need to obtain your Installation Id from the ./bwdata/env/global.override.env configuration file on your server in order to generate the file, or you can also get it from the Bitwarden System Administration Portal (https://{YOUR URL}/admin).

Once you have the new license file then you can log into your self-hosted Web Vault and go to Settings > Organizations > {YOUR ORG NAME} > Settings sub-tab (Gears Icon) > Subscription and apply it there. After applying the new license file, you will want to log out and log back in to make sure the disabled message has cleared.

**Comment by clayadams5226** [comment]
Hi @paradoxicalNL , it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Comment by ralvarezba** [comment]
Hi,

We did installed a Selfhosted and have this same issue.  After doing the payment and downloading, and trying to upload to the specified user we got the message "this licese is not valid for this user"

Our installation is docker.  Bitwarden version: Version 2.27.0

I wonder if pro license can be used on selfhosted.

Thanks

**Comment by eliykat** [comment]
@ralvarezba, you can absolutely use premium and organization licences on self-hosted instances. Please contact our Customer Success team here: https://bitwarden.com/contact/ and they'll help you set it up.

**Comment by eliykat** [comment]
Hi again @paradoxicalNL, if you'd like help with your issue please contact our Customer Success team here: https://bitwarden.com/contact/. They'll help you debug it and they can escalate it if required. You can include a link to this Github issue so you don't have to explain it all over again. Thanks!

**Comment by paradoxicalNL** [comment]
> Hi again @paradoxicalNL, if you'd like help with your issue please contact our Customer Success team here: https://bitwarden.com/contact/. They'll help you debug it and they can escalate it if required. You can include a link to this Github issue so you don't have to explain it all over again. Thanks!

Thank you. I always ran my server without the license and it worked fine like that. I am currently exploring 1 option, as I run an apache2 proxy server in front of my local bitwarden instalaltion, that might cause this issue. I will contact them if needed.
