### ISSUE TITLE
"ADD FOLDER" action is not working.

### ISSUE THREAD

**Issue by dominicoder** [bitwarden/server#1257]
I recently moved to BitWarden from LastPass and have been migrating my passwords. I have created multiple folders without issues. Today however I'm encountering an error that occurs on all platforms I've tried: FireFox extension, MacOs App, bitwarden website (on FireFox), and the Android App, so it would appear to be a server side issue.

**Steps:**
Just try to add a new folder on any platform.
The app will spin for a bit then fail.
Error message (title and subtitle) is the same regardless of platform:
**"An error has occurred."
"An unhandled server error has occurred".**

Renaming or deleting existing folders works just fine.

**Comment by eliykat** [comment]
I've done a quick test and haven't been able to recreate this. Can you please contact our customer success team, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. They'll help you troubleshoot it, and they'll log it as a bug if it's reproducible. The issue here will be closed. Thanks!

**Comment by dominicoder** [comment]
OK - I'll give that a shot. Thanks for the prompt reply.

**Comment by dominicoder** [comment]
Actually - just tried again and now it works. 🤷
