### ISSUE TITLE
Error in bitwarden-web: Failed to create CoreCLR, HRESULT: 0x80004005

### ISSUE THREAD

**Issue by chrisklpp** [bitwarden/server#1258]
I tried to install bitwarden and followed the guide on the homepage:
[https://bitwarden.com/help/article/install-on-premise/](url)
I created a new user 'bitwarden' as recommended. 
The bitwarden-web container keeps restarting, making the installation inaccessible. 
`docker logs bitwarden-web` returns a long list of the same error message: `Failed to create CoreCLR, HRESULT: 0x80004005`

I am running ubuntu 20.04 LTS and:
`bitwarden.sh version 1.40.0`
`Docker version 20.10.5, build 55c4c88`
`docker-compose version 1.24.0, build 0aa59064`

Any help is appreciated and I can happily provide more logs if there's anything useful I am missing.

**Comment by clayadams5226** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
