### ISSUE TITLE
Sort the passwords by strength

### ISSUE THREAD

**Issue by DrDzy01** [bitwarden/server#1280]
There are plenty of password and some of them are created long times ago, I must find them out and make a stronger one

**Comment by eliykat** [comment]
You can use the Weak Passwords Report (and other available reports) to do this: https://bitwarden.com/help/article/reports/

You will be able to sort them by severity in the next release: https://github.com/bitwarden/web/pull/446

If I've misunderstood you and you are requesting a different feature, you can do so on our community forums. More information on that below.

---

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by DrDzy01** [comment]
Thanks
