### ISSUE TITLE
Allow Specific Users to bypass policies SSO or MFA

### ISSUE THREAD

**Issue by winklevos** [bitwarden/server#1295]
Allow admin to add groups or specific users to bypass SSO login requirement or MFA requirement, very useful in CLI application

**Comment by Greenderella** [comment]
Hi @winklevos 

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests).

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

Thanks!

**Comment by eliykat** [comment]
Hi @winklevos, you have a couple of options for bypassing SSO/MFA requirements in the CLI app:
* Recommended: use the `--apikey` switch: see [here](https://bitwarden.com/help/article/cli/#using-an-api-key) for instructions
* Also, owners and administrators are exempt from SSO/MFA policies. I don't think you should elevate privileges just to get around this requirement, but if you're already using an owner/administrator account in the CLI app, it's useful to know.

I'll now close this for the reasons given above.

**Comment by winklevos** [comment]
Hey @eliykat 

I have tried using --apikey but this does not bypass MFA or SSO requirements

And i would like to avoid giving owner/admin for this

**Comment by eliykat** [comment]
Hey @winklevos, can you please reach out to our customer success team using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. They'll help you troubleshoot it and hopefully get it working. If it is a bug, then they'll reopen this issue and we can investigate it further at this end.

**Comment by winklevos** [comment]
Thanks @eliykat they have created https://github.com/bitwarden/cli/issues/297 as they could recreate the issue
