### ISSUE TITLE
Ports in global.override

### ISSUE THREAD

**Issue by ben-bole** [bitwarden/server#1306]
Hello out there,
my Bitwarden environment is accessible through a DynDNS service. Because I have my main server running on the standard https port 443 Bitwarden logically cant use that port. So I am using another 3-digit port.
Pressing on links in authorization mails results in seeing the web GUI of my main server, because Bitwarden points to 443 and not the port configured in my OPNSense server.

I think the solution should be just changing the `globalSettings__baseServiceUri__admin` etc. values to the url with the port as a suffix.

Has anyone experiences with that? Or are you pointing a subdomain at your Bitwarden server?

Thank you in advance,
Benedict

**Comment by eliykat** [comment]
The response here indicates that setting your base URIs is indeed the answer: https://github.com/bitwarden/web/issues/555

I checked the code and it uses `globalSettings__baseServiceUri__vaultWithHash` and `globalSettings__siteName` to generate the links in emails.

I also see a few recommendations around to use a reverse proxy rather than specifying ports in your config, but I don't know if that's essential.

We use Github to track bugs and other development issues. If you need more help configuring your self-hosted instance, please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. This issue will now be closed.
