### ISSUE TITLE
installation on oracle armv8

### ISSUE THREAD

**Issue by surihost** [bitwarden/server#1368]
Hi,

How to install bitwarden on oracle armv8 instance ?

**Comment by eliykat** [comment]
Thanks for getting in touch! We use GitHub issues as a place to track bugs and other development related issues. If you'd like help using or configuring Bitwarden, please contact our Customer Success team here: https://bitwarden.com/contact. You can include a link to this issue in the message content. You can also search for an answer in our [help documentation](https://bitwarden.com/help/) or get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/). The issue here will be closed.
