### ISSUE TITLE
Duplicate/Copy shared entrys not possible in web Vault

### ISSUE THREAD

**Issue by Flol0** [bitwarden/server#1373]
## Describe the Bug
Duplicate shared entrys only possible in the Bitwarden Client not in the Web Vault

## Steps To Reproduce
try to duplicate/copy shared entrys in web vault

## Expected Result

being able to copy/duplicate in web vault

## Actual Result

I don`t see a button to copy/duplicate

## Environment

- Operating system: Windows 10
- Build Version: 1.41.3
- Self Hosted: true
- Environment: Docker

**Comment by kendratodd** [comment]
Hi @Flol0, I'm not able to reproduce this on the Web Vault. Have you tried cloning the shared item from the Organization vault? Right now, shared items cannot be cloned from the Individual Vault, which is why you may not see the Clone option in the dropdown. There's a bit more info available here: https://bitwarden.com/help/article/managing-items/#clone-vault-items

Please let me know if that works for you! Thanks!

**Comment by Flol0** [comment]
Hello,

Yes you are right. Now it works.
Was my fault..

**Comment by kendratodd** [comment]
No problem - thanks for the quick feedback ⚡
