### ISSUE TITLE
Bitwarden Send and domain redirects not working

### ISSUE THREAD

**Issue by MarjobIf** [bitwarden/server#1456]
I noticed that a "Bitwarden send" doesn't work when using domain redirects.

Our self-hosted instance runs, for example, via bitwarden.hetzner.firmname.com and we also forward to it from bitwarden.firmname.com (CNAME).

The download of a send created by bitwarden.firmname.com does not work, whereas a send from bitwarden.hetzner.firmname.com works.

The sends use a correspondingly different link:

https://bitwarden.hetzner.firmname.com/#/send/W9S8vYs0-_061gAH3LAg3nG0ebLs5Fq-Ru2p7Aw -> working

https://bitwarden.firmname.com/#/send/W9S8vYs0-_061gAH3LAg3nG0ebLs5Fq-Ru2p7Aw -> not working

## Steps To Reproduce

1. HTTP GET to '...'
2. Copy response and HTTP POST to '....'
3. Run command '....' via CLI
4. Validate response has '...'

## Environment

- Operating system: [e.g. Cloud, Windows 10, Mac OS Catalina]
- Build Version: [e.g. 1.42.0]
- Self Hosted: [true/false]
- Environment: [e.g. Cloud, Docker, EKS, ECS, K8S]
- Hardware: [e.g. Intel 6-core, 8GB RAM]

**Comment by SergeantConfused** [comment]
Hi @MarjobIf,

Can you please get in touch with us using this contact form: https://bitwarden.com/contact/ and describe how your Bitwarden server is set up? It would be very helpful if you could also include a link to 2 screenshots showing the errors you're getting in your Network and Console tabs from your browser's Developer Tools.


Thank you in advance,

**Comment by clayadams5226** [comment]
Thanks for getting in touch! Please contact our Customer Success team here: https://bitwarden.com/contact. You can include a link to this issue in the message content. You can also search for an answer in our [help documentation](https://bitwarden.com/help/) or get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/). The issue here will be closed.
