### ISSUE TITLE
Updating the security stamp should delete device records

### ISSUE THREAD

**Issue by winterqt** [bitwarden/server#1493]
When deauthorizing sessions in the web client, a request is sent to to `/accounts/security-stamp`. This updates the security stamp, which (as far as I know) deauthorizes all sessions.

However, this doesn't affect the "New Device" emails, because the device records aren't removed, which is what is used to determine if a device is new or not.
One can delete these devices by making a request to `/devices`, and then `DELETE /devices/{id}`, but the server will never do this on its own. (and there's no exposed UI for this)

I believe that deauthorizing all sessions is the perfect opportunity for the server to delete these records, which will allow users to audit their logins further.

**Comment by clayadams5226** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
