### ISSUE TITLE
Bitwarden unneedet temp files delete on ubuntu

### ISSUE THREAD

**Issue by basti2015** [bitwarden/server#1566]
Which folder and files can I delete to get more free space?
I have install bitwarden on Ubutu 20.04.2 LTS
My usage memory are 99,8% of 23,74 GB

**Comment by djsmith85** [comment]
Hi @basti2015, Thanks for getting in touch! We use GitHub issues as a place to track bugs and other development related issues. 
As this is not directly related to Bitwarden or an issue with Bitwarden, I suggest you check out our [help documentation](https://bitwarden.com/help/) or get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/). 

As a quick tip, I would have a look if there are any log files you can delete or check if you have older/unused docker images on your system.

The issue here will be closed.
