### ISSUE TITLE
Bitwarden can't recognize the official Brazilian Government gov.br website as a website

### ISSUE THREAD

**Issue by thomasbbrunner** [bitwarden/server#1568]
## Describe the Bug

I am creating this issue here, as I believe that the database of allowed domains and suffixes is part of this repo. If this is not the relevant place, I'll delete this issue and add it to the corresponing repo.

The official Brazilian Government website `gov.br` is not identified as a valid website by the Bitwarden. 

When using the default match detection, the website can't be launched. The Chrome extension and the mobile app do not automatically suggest the vault entry when logging into the website.

By adding `https://` before the website, the extension is able to launch the website. However, it still can't automatically  autofill the login details.

I believe this is because `gov.br` is also a valid domain suffix for government websites, so Bitwarden does not recognize it as a valid website.

This is a problem with the browser extensions, the web interface *and* the mobile app.

## Steps To Reproduce

1. Create entry with website `gov.br` or `https://gov.br` or `www.gov.br` using the default match detection.
2. Go go `gov.br`
3. The extension *will not* suggest the entry for autofill

## Expected Result

1. Create entry with website `gov.br` or `https://gov.br` or `www.gov.br` using the default match detection.
2. Go go `gov.br`
3. The extension *will* suggest the entry for autofill

## Environment

- Operating system: Ubuntu 21.04 using the Chrome extension

**Comment by eliykat** [comment]
Hi @thomasbbrunner, I don't think this is related to allowed domains or suffixes. Here's what I did to get this site working.

1. I went to `gov.br` and then clicked "Entrar"
2. That link takes you to `https://sso.acesso.gov.br/`. That might be why `gov.br` isn't working for you with the default match detection. Make sure that the URI in your Bitwarden entry is the same as the URI on the login page (not necessarily the homepage) - or play with your match detection settings.
3. The first step of the login form expects a CPF number, and the HTML `id` on the input element is `accountId`. That isn't picked up by our autofill script, which looks for a "username" (or similar). However, you can create a custom field using the instructions [here](https://bitwarden.com/help/article/custom-fields/) so that it picks up and autofills this field.
4. I couldn't get further than here because I don't have a CPF, but if you have trouble filling the password field, you should be able to create a custom field for that as well.

Using this process I was able to create a login, launch the site, and autofill the CPF number.

If you need further assistance setting up your URI matching or custom fields, you can:
* contact our Customer Success team here: https://bitwarden.com/contact. You can include a link to this issue in the message content. 
* search for an answer in our [help documentation](https://bitwarden.com/help/) 
* get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/).

We're also collecting a list of sites where default autofill doesn't work, and you can add your report there if you like. That will help us improve autofill in the future: bitwarden/browser#1621.

This issue will now be closed. Thanks!
