### ISSUE TITLE
Issues updating from 1.43.0 to latest version.

### ISSUE THREAD

**Issue by joshncori** [bitwarden/server#1677]
### Steps To Reproduce

Following the Bitwarden update guide, I enter this in my terminal session;

     1- sudo ./bitwarden.sh updateself
     2- sudo ./bitwarden.sh update

### Expected Result

My Bitwarden should update to the latest version according to the admin page.  

Server Installed
1.43.0 
Server Latest
1.44.1
Web Installed
2.23.0 
Web Latest
2.24.1

### Actual Result

bitwarden.sh version 1.43.0
Docker version 20.10.10, build b485636
docker-compose version 1.29.1, build c34c88b2

Update not needed

### Screenshots or Videos

![1](https://user-images.githubusercontent.com/62454060/139495688-dff46053-64e2-47d4-bc81-2a74d13461b3.jpg)
![2](https://user-images.githubusercontent.com/62454060/139495691-0d4b4c70-18e7-493b-a67b-4b08aeaf6bd9.jpg)

### Build Version

1.43.0

### Environment

Self-Hosted

### Environment Details

Ubuntu 20.04.3

**Comment by akalsnes** [comment]
It is because they did not update the versions in this script yet: https://github.com/bitwarden/server/blob/master/scripts/bitwarden.sh

It is possible it was a conscious decision. It is also possible that someone forgot or some process failed.

**Comment by tgreer-bw** [comment]
We consciously don't update it immediately so we can monitor the cloud hosted behavior in the event we need to make any patches/updates. We'll make it available shortly 👍

**Comment by joshncori** [comment]
Okay, I was concerned because I missed the last couple updates.  I thought I may have something wrong with my installation.  I have been able to get the previous updates, just these last couple I have not been able to get.  Thank you for your quick response and I appreciate all you guys do.  I have been trying to stay more up to date with Bitwarden and just want to make sure my self hosted environment is at the latest secure update.

Thank you

**Comment by DvdGiessen** [comment]
@tgreer-bw Is there any way to be notified when a new release is made available for self-hosting?

Currently I am subscribed to receive release notifications, but those are sent out whenever a new release is made, not when the scripts are updated so that self-hosted setups may be updated. That means that now whenever I receive a notification, I have to manually keep checking the repository to see when I can actually install this update.

Especially for security-sensitive updates I can imagine it would be very desirable to receive an notification that can result in immediate action, instead of having to manually poll to see when that update becomes actually available.

The [recent addition to subscribe to release notes](https://community.bitwarden.com/t/send-release-announcements-notifications-to-subscribers/33837) doesn't seem to address this.

Perhaps GitHub releases in this repo can be created later (from the already pushed tag), or something along those lines.

**Comment by tgreer-bw** [comment]
@DvdGiessen - fair point. 

We're working on a way to make this clearer. We use the releases that are built via GitHub actions to deploy the cloud services, too, so we want to make sure it's clear when a 'release' happens. But - to your point, we also want to be clear when a release may be cloud-only (i.e. patch/config change, etc) or available for self-host update.

**Comment by djsmith85** [comment]
Closing this as the original question has been answered. As @tgreer-bw has mentioned we'll be working on improving the notification of updates (cloud and self-hosted).

**Comment by fnordpojk** [comment]
This has happened again with 1.45/2.25, and it is quite frustrating - the admin dashboard claims that I am not running the latest version and that I should update:
![image](https://user-images.githubusercontent.com/2369999/146217844-89c9d9e5-2987-4db2-b10f-536d498fa022.png)
..but the bitwarden.sh script is not updated and thinks everything is up to date.

How is the update notification work going? Is there a point to having an update check in the admin dashboard if I can't update anyway?
