### ISSUE TITLE
Update.sh not working

### ISSUE THREAD

**Issue by ebiscaia** [bitwarden/server#1792]
### Steps To Reproduce

Move to folder where .bitwarden.sh is located
Run
`sudo ./bitwarden.sh updateself; sudo ./bitwarden.sh update; sudo ./bitwarden.sh restart `

### Expected Result

New version of Bitwarden container being downloaded, installed and service restarted

### Actual Result

Error message

`bitwarden.sh version 1.44.1`
`Docker version 20.10.11, build dea9396e184290f638ea873c76db7c80efd5a1d2`
`Traceback (most recent call last):`
`File "/usr/bin/docker-compose", line 33, in <module> sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())`
`File "/usr/bin/docker-compose", line 22, in importlib_load_entry_point for entry_point in distribution(dist_name).entry_points
`File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution return' 'Distribution.from_name(distribution_name)`
`File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name raise PackageNotFoundError(name)`
`importlib.metadata.PackageNotFoundError: No package metadata was found for docker-compose`

### Additional Context

This started to happen after a couple of days. Not sure if it is related with my upgrade to Alpine Linux 3.15 or any other upgrade afterwards

### Build Version

1.44.1

### Environment

Self-Hosted

### Environment Details

OS: Alpine Linux v3.15 x86_64
Host: KVM/QEMU (Standard PC (i440FX + PIIX, 1996) pc-i440fx-6.1)
Kernel: 5.15.12-0-lts
CPU: Common KVM (4) @ 3.092GHz
Memory: 1630MiB / 2980MiB

Python
Installed:                                      Available:
python3-3.10.1-r0                       = 3.10.1-r0

Docker-compose
Installed:                                             Available:
docker-compose-1.29.2-r1                = 1.29.2-r1

Thanks

**Comment by Hinton** [comment]
This seems to be related to your environment. I found a reddit post suggesting that rebuilding the python packages might work, https://www.reddit.com/r/archlinux/comments/rf6c84/psa_python_310_is_in_core_rebuild_your_aur/.

Thanks for getting in touch! We use GitHub issues as a place to track bugs and other development related issues. If you'd like help using or configuring Bitwarden, please contact our Customer Success team here: https://bitwarden.com/contact. You can include a link to this issue in the message content. You can also search for an answer in our [help documentation](https://bitwarden.com/help/) or get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/). The issue here will be closed.
