### ISSUE TITLE
Can't invite a new user on organization

### ISSUE THREAD

**Issue by delucca** [bitwarden/server#1986]
### Steps To Reproduce

1. Go to a organization
2. Click on "Manage"
3. Go to "People"
4. Click on "Invite user"
5. Enter user details and try to invite it

### Expected Result

The user should be invited to the organization

### Actual Result

We receive a 500 error from the server, with the following message:
```
An error has occurred.
An unhandled server error has occurred. 
```

### Build Version

Cloud

### Environment

Cloud (bitwarden.com)

**Comment by aj-bw** [comment]
Hi @delucca !
Thank you for getting in touch and bringing this to our attention! I see this was posted a week ago, currently there are no reported issues at https://status.bitwarden.com/. However, we'd like to assist you further. We ask that you please contact us using our contact page, here: <https://bitwarden.com/contact.> You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.

**Comment by PureTryOut** [comment]
Uh not sure why this is closed? In the company I work for we're investigating possible password manager options but right now this is preventing us from inviting anybody to the organization we have created on https://bitwarden.com as a trial. After 2 invites this started occurring and now we're stuck. Rather than moving things to a private help desk somewhere, can we keep track here in public of what seems to be an actual bug? The default Bitwarden web client shouldn't have the ability to make the server break on an internal server error :wink:

**Comment by dwbit** [comment]
> Uh not sure why this is closed? In the company I work for we're investigating possible password manager options but right now this is preventing us from inviting anybody to the organization we have created on https://bitwarden.com as a trial. After 2 invites this started occurring and now we're stuck. Rather than moving things to a private help desk somewhere, can we keep track here in public of what seems to be an actual bug? The default Bitwarden web client shouldn't have the ability to make the server break on an internal server error 😉

Thanks for the additional context/feedback! In this case, it appears that the seat limit may have been reached. To rule this out please connect with the support team for confirmation at [bitwarden.com/contact](http://bitwarden.com/contact). Based on the results, the developer team team can investigate further if needed.

**Comment by PureTryOut** [comment]
Ah I just found the limit on a free account is 2, so yeah that's almost definitely the seat limit. Thanks for the pointer!
I'm not a fan of moving discussions like this to private contact forms and issue trackers though. The issue here is the UI showing a vague non-descriptive error mentioning "internal server error" which makes the user think something has gone wrong, while it should just say the limit has been reached.
