### ISSUE TITLE
Billing sync fails with active sponsoring request

### ISSUE THREAD

**Issue by davidgvg** [bitwarden/server#2065]
### Steps To Reproduce

1.Complete steps on https://bitwarden.com/help/families-for-enterprise-self-hosted/
2. In admin panel click on 'manually sync' under organization - 'my organization'
3. Shows: Status enabled & Billing Synced!
4. Create sponsoring request on any account
5. Repeat step 2
6. Shows Status: Value cannot be null. (Parameter 'source') 

### Expected Result

Sync should work and sponsorship mail should be send.

### Actual Result

Shows Status: Value cannot be null. (Parameter 'source') 

Error from docker logs bitwarden-admin:
(Removed Organization id)
```

warn: Bit.Admin.Controllers.OrganizationsController[0]
      => SpanId:1caf0e6b5868af4f, TraceId:c2e44b8bc985dd4798630f741cc72714, ParentId:0000000000000000 => ConnectionId:0HMIGE6HSCLD6 => RequestPath:/admin/organizations/triggerbillingsync/----xxxxxxxxxxxxxxx-------- RequestId:0HMIGE6HSCLD6:00000002 => Bit.Admin.Controllers.OrganizationsController.TriggerBillingSync (Admin)
      Error while attempting to do billing sync for organization with id '----xxxxxxxxxxxxxxx--------'
      System.ArgumentNullException: Value cannot be null. (Parameter 'source')
         at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
         at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
         at Bit.Core.Models.Api.Response.OrganizationSponsorships.OrganizationSponsorshipSyncResponseModel.ToOrganizationSponsorshipSync() in /home/runner/work/server/server/src/Core/Models/Api/Response/OrganizationSponsorships/OrganizationSponsorshipSyncResponseModel.cs:line 26
         at Bit.Core.OrganizationFeatures.OrganizationSponsorships.FamiliesForEnterprise.SelfHosted.SelfHostedSyncSponsorshipsCommand.SyncOrganization(Guid organizationId, Guid cloudOrganizationId, OrganizationConnection billingSyncConnection) in /home/runner/work/server/server/src/Core/OrganizationFeatures/OrganizationSponsorships/FamiliesForEnterprise/SelfHosted/SelfHostedSyncSponsorshipsCommand.cs:line 94
         at Bit.Admin.Controllers.OrganizationsController.TriggerBillingSync(Guid id) in /home/runner/work/server/server/src/Admin/Controllers/OrganizationsController.cs:line 199
```

### Additional Context

I noticed, even on a 'successful' sync with no active sponsorship request in the selfhosted instance under Organizations - Settings - Subscriptions - Billing Sync.  Last Sync still shows:  never. 
Even though the button in the admin panel states "Billing Synced!"

### Build Version

Server: 2022.5.1

### Environment

Self-Hosted

### Environment Details

Operating System: Ubuntu 20.4.3 LTS, up do date on updates, runs on lxc container on Proxmox VE
Environment: Docker installation via bitwarden.sh
Specs: 4GB Ram, 4 Cores

bitwarden.sh version 2022.5.1
Docker version 20.10.17, build 100c701
docker-compose version 1.25.0, build unknown

From Admin Panel:
Server Installed    2022.5.1 
Web Installed       2022.5.2

**Comment by justindbaur** [comment]
Hi @davidgvg Thanks for this great bug report. Could you reach out to [us privately](https://bitwarden.com/contact/) with the organization id from your license file? Or you can view it by going to your org from the cloud instance. I believe it reached us but we sent back something null when it shouldn't have been. I think their might be some helpful logs on our side we can look through to figure out this issue. 

Based on this though I will add better handling for our server response so we can give a better error. Regarding the info in your additional context, that is expected right now. The Last Sync time is based on a column from the sponsoring request. If there aren't any requests it doesn't have a time to go off of. We should change it to not show that "Billing Synced" though because no actual syncing happened. If there are no requests we don't reach out to our server to do the syncing.

**Comment by davidgvg** [comment]
Hey @justindbaur 
I just reached out to the bitwarden support via your link and provided the id's from the license file and the id from our selfhosted admin panel.
Something I noticed is, that the id in the admin panel is not the same as in the license file. Even after updating the license file again and doing a ./bitwarden.sh rebuild the organization id in the admin panel did not change. 

The id in the docker log message is the one from the selfhosted admin panel. 

I got the response from support to delete my sync token completely and  re-adding it. 
**This resulted in the sync being completed. And invite being send**
Important to note here is, that I already rotated the token a few times last week in my testing. It seems that somewhere the old token was still saved through multiply docker rebuilds and restarts. 

I will close this issue for now, if there is work to be done from your side feel free to reopen.

**Comment by justindbaur** [comment]
Hi @davidgvg
Thanks for the update. The id in your license file and selfhosted admin panel being different is totally expected. The id in the license file is from the org that was created in our cloud and from where your license file is downloaded. We have no knowledge of the id from the selfhosted side and we only send the id from the license file back to ourselves so we know what org to associate the sponsorship to on the cloud side. 

Another thing to add is that the token is stored directly in the database so docker rebuilds/restarts won't affect it. I do suspect that the token saved in your database and the one we were expecting on our side were different though. I will still add a few things so that hopefully both the admin portal and logs will be more helpful and pointing to the real issue. Thanks for your help on this!
