### ISSUE TITLE
Bitwarden send with files does not work. 

### ISSUE THREAD

**Issue by powerriegel** [bitwarden/server#2310]
### Steps To Reproduce

1. Go to Send, enter a name
2. Click on File and add arbitraty file, e.g. image
3. Click save

### Expected Result

File should be uploaded and a send created

### Actual Result

On Android it says "an error occurred" and kicks me out of my vault. On Linux desktop, the error says "your login expired" and kicks me as well. Same on Windows. 

Some days ago, I also had the error file size too large (500MB allowed) in ugly HTML tags, but my file has only 3MB. This error does not appear anymore after upgrade of my Bitwarden instance. 

### Build Version

2022.9.1 (5047)

### Environment

Self-Hosted

### Environment Details

This happens on ALL my clients
* Huawei Android 12
* Windows 11
* Ubuntu 22.04
I could never send a file using Bitwarden send. I'm a premium user. It works with text only.

**Comment by Hinton** [comment]
Hi @powerriegel,

This seems like an environment specific issue, and you should investigate the response and logs provided by the server.

**Comment by Larry-Sussman** [comment]
Hi @powerriegel, 
Are you still experiencing this issue? If so, this may be better handled by our dedicated Customer Success team.

Please contact us using our [Contact page](https://bitwarden.com/contact)[.](https://bitwarden.com/contact.) You can include a link to this issue in the message content for help in troubleshooting your environment.

The issue here will be closed. Thank you!
