### ISSUE TITLE
`globalSettings__mail__replyToEmail` is set as the contents in the `From:` entry of emails

### ISSUE THREAD

**Issue by UlyssesZh** [bitwarden/server#2345]
### Steps To Reproduce

My SMTP server does not allow a `From:` entry different from the email address of the sender. If I set `globalSettings__mail__replyToEmail` to a different email address, the email sending will fail.

### Expected Result

It should set the `Reply-To:` entry in the email instead of the `From:` entry.

### Actual Result

The `From:` entry is set as the contents of `globalSettings__mail__replyToEmail`.

### Build Version

2022.10.0

### Environment

Self-Hosted

### Environment Details

- Server OS: Arch Linux

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
