### ISSUE TITLE
No Firefow Relay option on self-hosted instance / DuckDuckGo fetch error

### ISSUE THREAD

**Issue by MuadDibIII** [bitwarden/server#2351]
### Steps To Reproduce

1. Go to a Bitwarden self-hosted instance
2. Click on Tools/Generator
3. Scroll down to select username generator

### Expected Result

I should see 5 options : 

- SimpleLogin
- AnonAddy
- Firefox Relay
- Fastmail
- DuckDuckGo

And when I generate a DuckDuckGo mail it should display a xxxxx@duck.com mail

### Actual Result

The Firefox relay option is missing and I have a fetch error using the duckduckgo option.

When I tried using the browser Firefox browser extension, I have all the 5 options and the DuckDuckGo worked whell.

### Screenshots or Videos

![Screenshot_20221020-112053_Firefox](https://user-images.githubusercontent.com/5659533/196910204-cc6a1754-5fd4-48fa-820f-0238a2defac6.jpg)

### Build Version

2022.10.0

### Environment

Self-Hosted

### Environment Details

Synology Docker install

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by justindbaur** [comment]
Hi @MuadDibIII, this is an issue with CORS and we are tracking that issue here bitwarden/clients#3798. CORS is why the Firefox Relay is not available on self hosted web and why the fix for DuckDuckGo will most likely be removed as well. I am going to close this issue in favor of the clients one because that is technically where the fix will need to happen.
