### ISSUE TITLE
Import Problem from Keepass

### ISSUE THREAD

**Issue by manny4566** [bitwarden/server#2613]
### Steps To Reproduce

Hi,
I want to import data over the "KeePass XML (2.x)" way, and get always a error without a description. 
A have test it with only one password in the import xml file, but get the same error.
What could be the problem and can i find more information about the error ?
Manually it is possible to create and store a password.
Thank you

### Expected Result

sucessful import

### Actual Result

Import error:
An unhandled server error has occurred.

### Additional Context

Bitwarden is a new installation form today via the documentation on premise.

### Build Version

2023.1.0

### Environment

Self-Hosted

### Environment Details

Debian 11.6
Docker version 20.10.23, build 7155243
Docker Compose version v2.15.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so, my KeePass 2 .xml test vault imports as expected.

We use GitHub issues as a place to track bugs and other development related issues. Please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
