### ISSUE TITLE
Ports not exposed in dockerfile (Plesk does not show Mappings)

### ISSUE THREAD

**Issue by Khamulus** [bitwarden/server#2673]
### Steps To Reproduce

Download and enable bitwarden/self-host:beta in a plesk environment

### Expected Result

Portmapping should be available

### Actual Result

No ports visible in plesk

### Additional Context

Plesk Dockerimplementation requires the used ports to be exposed in dockerfile do map to a webhost.
please add the "expose" lines to dockerfile, so an installation in plesk is possible

### Githash Version

-

### Environment Details

Centos 7.9
Plesk Obsidian 18.0.49

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/ 

Please sign up on our forums and search to see if this request already exists (https://community.bitwarden.com/signup). If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Note that the “Closed as not planned” status is for internal tracking purposes only, please do not hesitate to send us your suggestions to the forum.

Thanks!
