### ISSUE TITLE
Running on-prem bitwarden on non standard port sends wrong url in the verification email

### ISSUE THREAD

**Issue by rselbo** [bitwarden/server#2719]
### Steps To Reproduce

1. Host bitwarden on some non standard port e.g. bitwarden.example.com:444
2. Log in and click the verify email button 
3. The resulting verification link is without the port https://bitwarden.example.com/#/verify-email...

### Expected Result

The verification email should have a link with the port if the port is not 443. e.g. https://bitwarden.example.com:444/#/verify-email...

### Actual Result

The resulting verification link is without the expected port https://bitwarden.example.com/#/verify-email... causing the link to hit the wrong server and fail on certificate name mismatch.

### Build Version

2023.1

### Environment

Self-Hosted

### Environment Details

Ubuntu 20.04.5 LTS
Docker 
Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz, 16GB RAM

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there, 

I was unable to fully replicate this issue, however I will pass this to QA to look into it more

**Comment by roberto-sartori-gl** [comment]
@rselbo on Unified, it's possible to configured the BW_DOMAIN with the port (e.g. <my_url>:<port>) and the mails will be correct.
Maybe on the 'standard' client a similar option is available.

**Comment by joshtrichards** [comment]
I believe `globalSettings__baseServiceUri__vault` in `./bwdata/env/global.override.env` in Standard (which in Unified gets populated using `BW_DOMAIN` as an input).

Something like this in `./bwdata/env/global.override.env` I think should work:
```
globalSettings__baseServiceUri__vault=https://host.domain.tld:port
```

Make sure to rebuild/etc after - e.g.

https://bitwarden.com/help/environment-variables/

Note: This variable could probably benefit form being documented at the above URL since self-hosted installs are likely to encounter it often enough IMO.
