### ISSUE TITLE
Adding family organization is hidden

### ISSUE THREAD

**Issue by mtherien** [bitwarden/server#2743]
### Steps To Reproduce

1. Go to the vault
2. Click on new organization
3. Select choose file and select json file downloaded from vault.bitwarden.com
4. Click Submit

After a few minutes it will give an indication that the organization was added.  However, it does not appear under vaults for the user and you cannot access it.

If you login to admin, and select organizations, the organization is listed.

### Expected Result

Expect the organization to appear under all vaults after adding it.

### Actual Result

The vault does not appear and you cannot access it.

### Additional Context

I have tried restarting the Docker container and restarting the server that hosts the container.

### Githash Version

3cedc0c7-dirty

### Environment Details

- Operating system: Ubuntu 22.10
- Docker
- sqlite
- Raspberry Pi 3B

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by notnamed** [comment]
Hello

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in browser cache - restarting the Bitwarden container or the server does not necessarily clear the state of the Web Vault. You can try a hard refresh or your browser's incognito or private browsing mode to ensure cache is clear after uploading the Organization license file.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by mtherien** [comment]
As a developer, I clearly see this as a bug because the system did not respond as expected.  I did clear the browser cache, several times and tried an incognito mode instance with no solution. 

Since this is beta software, I would not expect you to provide support via your public contact form.  I did try searching for a resolution before posting an issue.  It's unfortunate that you quickly dismiss an issue because you cannot reproduce it without doing any troubleshooting.
