### ISSUE TITLE
Can't register with certain email address domains, ex: .media

### ISSUE THREAD

**Issue by joshua-russell** [bitwarden/server#2756]
### Steps To Reproduce

Attempt to register a user with a EXAMPLE.media email address.

### Expected Result

Users with non-standard email address domains should be able to register user accounts. 

### Actual Result

Receive unhandled error. 

### Githash Version

3cedc0c7-dirty

### Environment Details

self-host:beta

### Database Image

mariadb:jammy

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment]
Hi @joshua-russell,

I attempted to reproduce your issue and was unable to do so.  In particular, I was able to create an account for dave@example.media in the vault at https://vault.bitwarden.com.   I think your error could have its origin in a misconfiguration or network glitch.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by atjbramley** [comment]
Apologies - I missed the unified label so my previous test does not apply.  I'll test this again.

**Comment by atjbramley** [comment]
Hi @joshua-russell,

I attempted to reproduce your issue on the Unified Release and was unable to do so. I think your error could have its origin in a misconfiguration.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshootingIf your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
