### ISSUE TITLE
Unknown column 'u.AvatarColor' in 'field list' unified server

### ISSUE THREAD

**Issue by JonathanMurre** [bitwarden/server#2761]
### Steps To Reproduce

1. Install docker bitwarden/self-host with docker-compose.yaml
2. Go to /#/register
3. Create account
4. Check bitwarden/logs/identity.log 

### Expected Result

Account is created

### Actual Result

Error message

### Build Version

bitwarden/self-host:beta

### Environment

Self-Hosted

### Environment Details

- Mac OS
- Docker

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MarsCandyBars** [comment]
Hi there,

You haven't mentioned which database you used in your configuration, so we tried several different ones, but still could not reproduce the issue. I think your error could have its origin in a misconfiguration​, please double check your environment variables: https://bitwarden.com/help/install-and-deploy-unified-beta/#specify-environment-variables

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
