### ISSUE TITLE
Stream all logs to stdout/stderr

### ISSUE THREAD

**Issue by joerg** [bitwarden/server#2930]
### Steps To Reproduce

1. Install as documented
2. Run
3. Logs land in bwdata/logs

### Expected Result

All logs are streamed to stdout/stderr and can thus be captured by standard tools.

### Actual Result

Logs are captured in files on the disk which makes log evaluation and scaling of the service very hard (close to impossible).

### Additional Context

The ideal setup for Docker hosting would remove any requirement of lokal storage. As far as I can see, currently there are two things stored locally:
* Logs
* A data-protection key which seems to be something like the master key

Moving the logs to stdout/stderr and further moving the master key to some Environment Variable would enable a fully stateless setup.

### Githash Version

8d9ca424-dirty

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @joerg,

Thank you for your report. Your issue appears to be describing the intended behaviour. If you want this to be changed, it would be a feature request.

The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can create this request there so that it can be properly tracked.

We use GitHub issues as a place to track bugs and other development related issues; This issue will now be closed. 


Thank you again,
