### ISSUE TITLE
Bad authentications are not logged when unlocking

### ISSUE THREAD

**Issue by GeoCookie** [bitwarden/server#2932]
### Steps To Reproduce

1. Try to **unlock** my vault (windows app, edge addon, web) and type a wrong password
2. Got a message saying the password is wrong: ok
![image](https://github.com/bitwarden/server/assets/43962716/2258cf90-4376-40eb-89ec-e37432e5da77)

### Expected Result

I expect to see a new line "failed login attempt" in the file _bwdata/logs/identity/Identity/log.txt_

### Actual Result

No new lines are added to the file

### Additional Context

If I log out of Bitwarden and try to log back in with a wrong password...
![image](https://github.com/bitwarden/server/assets/43962716/ebfc2e24-823d-4498-a51d-26977f968f5a)

... a new line is correctly added to the log.txt file
![image](https://github.com/bitwarden/server/assets/43962716/9e3ecaf3-7edc-4667-856e-e8263d274294)

### Build Version

2023.4.3

### Environment

Self-Hosted

### Environment Details

- OS : Debian GNU/Linux 11 (bullseye)
- Environnement : Docker
- Deployment : with the script bitwarden.sh

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
Hi @GeoCookie 

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

You definitely shouldn’t expect to see a failed login attempt log line, because you are not logging in this should explain further; https://bitwarden.com/help/vault-timeout/

unlocking is client side, so maybe this should be a feature request. 

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
