### ISSUE TITLE
Organization Folders Showing in My Vault

### ISSUE THREAD

**Issue by fystemseet** [bitwarden/server#2945]
### Steps To Reproduce

1. Go to 'Vaults'
2. Create an Org Folder while selected on the Org Vault
3. Click on 'My Vault'

### Expected Result

I would expect the Organization folders to be available to select while All Vaults or the Organization Vault is selected.

### Actual Result

Organization folders are seen while My Vault is selected.

### Build Version

2023.4.3

### Environment

Self-Hosted

### Environment Details

- Operating System: Windows Server Standard 2022
- Runtime: Docker Engine v20.10.23
- Hardware: 2 Cores, 8 GB RAM

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @fystemseet,

Thank you for your report. Your issue appears to be describing the intended behaviour of the software. All the folders are displayed when focusing on the (All vaults) filter or (My vault) filter, even if some of these folders contain only organizational vault items. If you want this to be changed, it would be considered a feature request.

The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can create a request there so that it can be properly tracked.

We use GitHub issues as a place to track bugs and other development related issues; This issue will now be closed. 


Thank you again,
