### ISSUE TITLE
start up mssql error 101

### ISSUE THREAD

**Issue by baek-sang** [bitwarden/server#2998]
### Steps To Reproduce

[](https://bitwarden.com/help/install-on-premise-linux/)

### Expected Result

- no error

### Actual Result

```bash
$ docker logs -f bitwarden-mssql
/opt/mssql/bin/sqlservr: Unable to start the process, with error 101.

/opt/mssql/bin/sqlservr: Unable to start the process, with error 101.

/opt/mssql/bin/sqlservr: Unable to start the process, with error 101.

/opt/mssql/bin/sqlservr: Unable to start the process, with error 101.

/opt/mssql/bin/sqlservr: Unable to start the process, with error 101.

/opt/mssql/bin/sqlservr: Unable to start the process, with error 101.

/opt/mssql/bin/sqlservr: Unable to start the process, with error 101.

/opt/mssql/bin/sqlservr: Unable to start the process, with error 101.
```

### Additional Context

It seems to be related to selinux

### Build Version

2023.5.0

### Environment

Self-Hosted

### Environment Details

- OS : rockyliunx 9.2
- Env: docker
- HW: amd 2core, 4gb ram

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MarsCandyBars** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration of docker, how have you installed docker? Did this happen after an update? I recommend entering a support request so that we can investigate further.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
