### ISSUE TITLE
Self-hosted installation SMTP error

### ISSUE THREAD

**Issue by ajkelsey** [bitwarden/server#3026]
### Steps To Reproduce

New self hosted installed of Bitwarden. Created a new account. Attempted to send verification email. 

Also, the admin portal does not function and I believe it is related to my SMTP issue.

### Expected Result

I expected the email to be sent to my account.

### Actual Result

Email was not sent. received an SMTP error.

```
2023-06-17 17:00:16.016 +00:00 [Error] “Your IP: ***.***.***.*** : Your domain [example.com](http://example.com/) is not allowed in header From”
MailKit.Net.Smtp.SmtpCommandException: “Your IP: ***.***.***.*** : Your domain [example.com](http://example.com/) is not allowed in header From”
```

### Additional Context

The url for my bitwarden instance is resolved locally to a private ip. The IP referenced in the error message is a real IP for my router.

### Build Version

Version 2023.5.0

### Environment

Self-Hosted

### Environment Details

- OS: Ubuntu 22.04.2 LTS
- Docker 

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by tmknight** [comment]
On the surface, this seems a config issue vs bug.  Are the email addresses you are using real addresses or aliases; does your smtp solution allow aliases to be used to send; what are your smtp server logs showing?

**Comment by ajkelsey** [comment]
The email address is a real address. I don't have access to the smtp logs.

Here are my environment settings:
globalSettings__mail__smtp__port=465
globalSettings__mail__smtp__ssl=true

**Comment by tmknight** [comment]
The error is telling you what's wrong; if it's really returning errors about example.com, they you haven't provided valid configurations.

Besides the existing documentation, I also suggest you seek guidance at https://community.bitwarden.com/.

**Comment by ajkelsey** [comment]
I have reviewed to the documentation extensively, and I don't understand what "not allowed in header From" means.

**Comment by atjbramley** [comment]
Hi @ajkelsey 

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration - please see our guide to setting the SMTP settings for your installation here:

https://bitwarden.com/help/install-on-premise-linux/#post-install-configuration

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
