### ISSUE TITLE
Update procedure: seems as if only server updates are pulled

### ISSUE THREAD

**Issue by lastphoenx** [bitwarden/server#3030]
### Steps To Reproduce

1. login to bitwarden admin panel and check sreen for updates
2. follow update process for ducker compose (https://bitwarden.com/help/install-and-deploy-unified-beta/)
3. check bitwarden admin panel if updates are completed

### Expected Result

serever and web updates are made

### Actual Result

only server updates are made

### Screenshots or Videos

Dashboard
Welcome to the Bitwarden System Administration Portal.

VERSION
Server Installed
2023.5.0 
Server Latest
2023.5.0
Web Installed
2023.4.2 
Web Latest
2023.5.0

### Githash Version

1202a670-dirty

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
hi @lastphoenx 

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed.

**Comment by lastphoenx** [comment]
Hi @Adedamola-Aina 
Thx for reviewing and your hint about feature requests.
But I am not sure if are taking about the same thing, are you saying it is not intendet for self-hosted unified versions to upate web-gui as well and this is only for other self-hosted versions and explicit not povided for unified version?
