### ISSUE TITLE
Bitwarden fails silently when smtp is not configured properly

### ISSUE THREAD

**Issue by rcarrier-penega** [bitwarden/server#3327]
### Steps To Reproduce

1.Install bitwarden self hosted
2.Setup smtp with a bogus configuration
3.Access the admin page at domain.tld/admin
4. Enter valid email admin email address
5. Get redirected to a 404

There is also a similar problem when adding a user in the bitwarden page

### Expected Result

We should get the message a login email has been sent

### Actual Result

We get redirected to a 404 page

### Additional Context

There seems to be a lack of smtp validation in bitwarden and it triggers silent error everywhere in the app.

At the minimum, there should be a script in bitwarden.sh to validate smtp settings. 

Better handling of those error would make life easier for a lot of people.

### Githash Version

"2023.9.0"

### Environment Details

Rocky Linux 9, KVM 

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration of SMTP. Please take a look at this article in the help center: https://bitwarden.com/help/admin-portal/

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by rcarrier-penega** [comment]
Did you even read my ticket? Of course its caused by smtp misconfiguration.

However, configuring smtp correctly will not fix the subpar error handling in bitwarden.

Kind of like the subpar handling of this ticket. My opinion is that the feedback provided through github to improve the software is not being taken seriously. 

Seriously considering migrating to another solution after being faced with this lack of professionalism and interest in making the software better.
