### ISSUE TITLE
./bitwarden.sh rebuild overwriting config.yml

### ISSUE THREAD

**Issue by runofthemill** [bitwarden/server#3638]
### Steps To Reproduce

Following the "Docker -> Linux Standard Deployment":

1. After install, make a change to `/opt/bitwarden/bwdata/config.yml`
2. Confirm the change is persisted to disk
3. Run `/opt/bitwarden/bitwarden.sh rebuild`
4. Observe the change to `/opt/bitwarden/bwdata/config.yml` is no longer there

### Expected Result

Changes made to `config.yml` should not be overwritten when running `/opt/bitwarden/bitwarden.sh rebuild`

### Actual Result

`config.yml` reverts to defaults when running `/opt/bitwarden/bitwarden.sh rebuild`

### Build Version

2023.12.0

### Environment

Self-Hosted

### Environment Details

bitwarden.sh version 2023.12.0
Docker version 24.0.5, build 24.0.5-0ubuntu1~20.04.1
docker-compose version 1.25.0, build unknown

Ubuntu 20.04.6 LTS

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

I attempted to reproduce your issue by [changing the name of my server](https://bitwarden.com/help/hosting-faqs/#q-how-do-i-change-the-name-of-my-server ) (a task that requires modifying the ./bwdata/config.yml file) and the update completes successfully.

Something in your configuration could be preventing for the changes to be saved. You will probably want to check if after you make and save the changes, if you log out/exit the instance/VM/Server, and log back in, are you still able to see the changes?

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
