### ISSUE TITLE
Browser theme is not persistent across sessions.

### ISSUE THREAD

**Issue by RamonAbudAlcala** [bitwarden/server#3732]
### Steps To Reproduce

This is easily demonstrated using two devices.
Both browsers are in dark mode.

Device 1:
0. Login to self-hosted bitwarden unified instance.
1. Go to 'Account Settings -> Preferences -> Theme'
Note that the default is 'Light'
2. Select 'Dark'.

Device 2:
0. Login to self-hosted bitwarden unified instance.

### Expected Result

Expect default theme to be 'Dark'

Expect Device 2 to start with Dark theme.

### Actual Result

Device 2 starts with Light theme.

Alternatively, one may just delete the cookies in a single device.
It appears that theme settings are saved in a cookie instead of account-wide, or server-wide.

### Githash Version

581aec36-dirty

### Environment Details

Host: Debian Bookworm
Clients: Android, iOS, Linux, Windows.
Browser: Firefox.

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!
