### ISSUE TITLE
Bitwarden sends already used two-step login code (email)

### ISSUE THREAD

**Issue by MikeVerhees** [bitwarden/server#3735]
### Steps To Reproduce

1.  Open the bitwarden browser extension
2. input your username/password, use a clean install so you get a 2fa prompt.
3. input the 2fa code you receive in your mail.
4. You can successfully log in
5. Now go to vault.bitwarden.com
6. input your username/password
7. You will receive a 2fa prompt.
8. You receive a new mail containing the exact same code you received previously.
9. Use the code to sign in to vault.bitwarden.com
10. You get an error saying the code is not valid.

### Expected Result

I Expect to receive a new code, different from the one I used before & expect that one to work :)

### Actual Result

The same code as used before is mailed again, this one no longer works to login to the second client.

### Screenshots or Videos

![image](https://github.com/bitwarden/server/assets/7385347/3c7b30b9-788a-4a26-b7b4-e5cd3a2bee95)

### Additional Context

This also happens when using mobile clients, desktop client or any other combination of clients.

### Build Version

Client does not seem to matter.

### Environment

Cloud (bitwarden.com)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi @MikeVerhees, at the moment this is the expected behavior for the current email 2FA implementation. We have an internal task on our backlog to implement a unique code for each email.

At the moment, the current TOTP timeout is 5 minutes. You will need to wait for 5 minutes to receive a new code and be able to attempt login again.

We use GitHub issues as a place to track bugs and other development related issues. This issue will now be closed.

We thank you for bringing this to our attention, and for your understanding. If you have any further questions, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
