### ISSUE TITLE
Bitwarden Unified - Nginx - Permission denied - Since Update - See Issue 2567 

### ISSUE THREAD

**Issue by tk7507** [bitwarden/server#3817]
### Steps To Reproduce

Updated to bitwarden/self-host:beta

Result:
2023-01-11 15:15:48,962 INFO RPC interface 'supervisor' initialized
2023-01-11 15:15:48,962 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2023-01-11 15:15:48,963 INFO supervisord started with pid 52

Updated back to bitwarden/self-host:2024.1.2-beta

Working again

Tested workaround of Issue 2567 : 
No, result. But Folders were not created

docker exec {Container name} mkdir /var/lib/nginx/tmp/client_body
docker exec {Container name} mkdir /var/lib/nginx/tmp/proxy
docker exec {Container name} mkdir /var/lib/nginx/tmp/fastcgi
docker exec {Container name} mkdir /var/lib/nginx/tmp/uwsgi
docker exec {Container name} mkdir /var/lib/nginx/tmp/scgi

### Expected Result

No CRIT fault

### Actual Result

CRIT fault

### Build Version

beta

### Environment

Self-Hosted

### Environment Details

Synology

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Hi @tk7507 and thank you for your report.

There have been some updates to the dev and beta release, since your report, which have resolved issues (https://github.com/bitwarden/server/issues/3755, https://github.com/bitwarden/server/issues/3820) and might be related to yours.

Could you please test with the latest release and let us know if this resolves your issue?

Kind regards,
Daniel
