### ISSUE TITLE
Unable to update locally hosted instance due to supposedly missing docker-compose.yml

### ISSUE THREAD

**Issue by DaneRainbird** [bitwarden/server#3883]
### Steps To Reproduce

1. Navigate to the Bitwarden directory
2. Run `./docker.sh update`
3. Observe the error message `stat /opt/bitwarden/bwdata/docker/docker-compose.yml: no such file or directory`

### Expected Result

Bitwarden updates itself as per the [instructions](https://bitwarden.com/help/updating-on-premise/)

### Actual Result

The update script fails due to the docker-compose.yml file supposedly not existing, however the file definitely exists:

```bash
bitwarden@<server>:/opt/bitwarden$ ./bitwarden.sh update
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2024, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 2024.2.3
Docker version 25.0.3, build 4debf41
Docker Compose version v2.20.3

stat /opt/bitwarden/bwdata/docker/docker-compose.yml: no such file or directory
bitwarden@<server>:/opt/bitwarden$ stat /opt/bitwarden/bwdata/docker/docker-compose.yml
  File: /opt/bitwarden/bwdata/docker/docker-compose.yml
  Size: 4900            Blocks: 16         IO Block: 4096   regular file
Device: fd00h/64768d    Inode: 12320822    Links: 1
Access: (0700/-rwx------)  Uid: ( 1003/bitwarden)   Gid: ( 1003/bitwarden)
Access: 2024-03-09 10:25:57.337793103 +1100
Modify: 2023-10-29 20:08:48.544711275 +1100
Change: 2023-10-29 20:08:48.544711275 +1100
 Birth: 2023-10-28 23:10:51.607605403 +1100
```

### Build Version

bitwarden.sh version 2024.2.3

### Environment

Self-Hosted

### Environment Details

Ubuntu 22.04.4 LTS x86_64
bash 5.1.16
Docker version 25.0.3, build 4debf41

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hello @DaneRainbird,

Thank you for reporting this. I am unable to reproduce this, and I suspect it's related to your particular environment. Please consider running (rebuild) and then (restart), and then (updateself) and then (update); Whatever you do, make sure to back your host up, or mirror it, so that you'd be able to roll back to a working-state if things do not go smoothly.

If this behaviour persists, please create a [Support ticket](https://bitwarden.com/help/) so we'd have a look at this together, and please also include a link to this GitHub report in the body of your ticket.

Alternatively, you can seek assistance from other Bitwarden users in our [Community Forums](https://community.bitwarden.com/c/support/), if you wish.

We use GitHub track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,
