### ISSUE TITLE
Closing: BWN-01-008 – Malicious API server could steal organization encryption keys

### ISSUE THREAD

**Issue by paragonie-scott** [bitwarden/server#392]
Despite what [the Cure53 audit report](https://cdn.bitwarden.net/misc/Bitwarden%20Security%20Assessment%20Report%20-%20v1.pdf) says, this isn't an intractable problem. Solving it isn't drop-dead-simple, but 90% of the work is done already. The problem is related to the problem of [secure code delivery](https://defuse.ca/triangle-of-secure-code-delivery.htm) although with focus almost exclusively on public keys rather than update files.

* https://github.com/paragonie/chronicle#userbase-consistency-verification
* https://github.com/paragonie-scott/public-projects/issues/5

All you need to do is maintain an append-only cryptographic ledger of Bitwarden servers and their public keys. [Chronicle](https://paragonie.com/blog/2017/07/chronicle-will-make-you-question-need-for-blockchain-technology) was specifically designed for these sorts of use-cases.

Then you can simply add a process publish all servers' public keys into this ledger. This allows you to build an independently auditable history of all public-key <-> identity associations. Any attempt to backdoor a Bitwarden user will be irrevocably detectable, since attackers will have to announce their presence to all users in order for any user to accept their malicious public key.

Not only does this provide confidence that nobody has provided a malicious public key, it also serves as a legal deterrence to nation states that cannot compromise computers in their own country (i.e. NSA).

This deterrence is a consequence of the userbase consistency feature: **In order to compromise *anyone*, you have to put *everyone* at risk.** Additionally, you abandon all stealth in doing so.

**Comment by kspearrin** [comment]
Thanks for the suggestion, however, I am not sure I understand how this would fit into the a design to provide public key authentication to the Bitwarden clients

1. API server publishes users and their associated public keys to this ledger?
2. Somehow the clients validate the returned API public keys with this ledger? How would that be done?

I am coming at this with no experience in using Blockchain technologies before, though I do have a bssic understanding of how they work.

**Comment by Hinton** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
