### ISSUE TITLE
bitwarden.sh won't updateself to 2024.3.0

### ISSUE THREAD

**Issue by lateparty** [bitwarden/server#3924]
### Steps To Reproduce

1. Go to the directory bitwarden.sh is located
2. run ./bitwarden.sh updateself
3. command runs successfully but stays on 2024.2.3

### Expected Result

That it updates to 2024.3.0 as it was released over 4 days ago.

### Actual Result

Stays at current 2024.2.3

### Screenshots or Videos

Time stamped screenshot below:
![Screenshot_2024-03-25_15-40](https://github.com/bitwarden/server/assets/20498775/f040f9d0-385a-455a-8435-c99dadad568f)

### Build Version

2024.2.3

### Environment

Self-Hosted

### Environment Details

- Operating System - Arch Linux
- Environment - Docker
- Hardware - Intel 4P / 8E core & 32GB of RAM

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in not running all required commands as outlined in this help article: https://bitwarden.com/help/updating-on-premise/

I'd also recommend running `./bitwarden.sh rebuild` once you've completed those steps to rebuild the containers.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by lateparty** [comment]
Feels like a joke reply. Sorry for not being so explicit in expressing that of course I ran ./bitwarden.sh update afterwards. It just spat out update not needed. I also ran a rebuild and I am still on 2024.2.3 - I would appreciate some better assistance.

Happy to provide screenshots as needed but I would like to think I am being taken seriously first.

**Comment by djsmith85** [comment]
@lateparty The self-hosted release is delayed a couple of days of the cloud server release, to ensure any issues are identified and fixed before also rolling out self-hosted.

`2024.3.0` for self-hosted is now available: https://github.com/bitwarden/self-host/releases/tag/v2024.3.0
