### ISSUE TITLE
Umlauts in csv import don't work

### ISSUE THREAD

**Issue by UkeHa** [bitwarden/server#395]
Hi,
if you import a csv-file (bitwarden format) german Umlauts in descriptions show up as �. This affects at least "öäü ÖÄÜ".
EDIT: It also affects 'ß' in an UTF-8 encoded file

**Comment by kspearrin** [comment]
Sounds like you need to adjust the text encoding in whatever program you are using to read it.

**Comment by Zoba273** [comment]
saved the file in excel as utf-8 and latin-1250 and the problem persists.

**Comment by xenji** [comment]
I would to offer my help to investigate it, if you like. 
@Zoba273 Would you be able to provide a sample file without disclosing any sensitive data?

Things to check that come into my mind:
- [ ] Is it correctly persisted in the database?
- [ ] If so, does the webpage have the correct output encoding?
- [ ] Any transcoding in between?

**Comment by Zoba273** [comment]
I don't think i can provide a sample file. I'll try to recreate another file that doesn't disclose any data.
How do i check the data in the database?
The webpage does **not** have the correct output - which is how i found the bug in the first place

I exported an empty csv file from bitwarden so i'd have a template. Afterwards i've filled my data into the same sheet (using excel - to keep my sanity). Then i've imported the data back into bitwarden, where the newly created Logins showed up as the character above (�)

**Comment by xenji** [comment]
Hey @Zoba273 ,
I guess that came not across as I intended. These tasks/thoughts are not for you personally, but for whoever starts an investigation. If you like to approach then, sure, feel free. You can use e.g. Microsofts SQL Studio (https://docs.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-2017) if you are on windows. Alternatively you can use a trial version of Data Grip to connect to the server. I must admit, I've never connected to a dockerized instance of SQLServer, therefore I cannot give you more guidance on that part.

The website output encoding refers to the content encoding set by the webserver and/or the meta tags in the HTML output. This particular task is meant to investigate if a display error is present or if the problem is somewhere else in the stack.

I hope this clarifies my previous comment a bit better.

**Comment by Zoba273** [comment]
I've looked into it and not only the description but also the password data is affected.

**Comment by Hinton** [comment]
The server itself doesn't perform CSV imports but rather the clients. If you are still experiencing this issue could you open a new ticket in [jslib](https://github.com/bitwarden/jslib/) with a re-produceable csv file for testing?

Thanks.
