### ISSUE TITLE
HELO issues

### ISSUE THREAD

**Issue by ninji** [bitwarden/server#4062]
### Steps To Reproduce

1. mail did not received by new user
2. changing SMTP server to our mail server shows HELO issues (see below)
3. outside the docker environment all FQDN are set, at self hosting server and in DNS
4. not sure when SMTP protocol is terminated
5. not sure if inside the docker the FQDN of sending server is known 

### Expected Result

BW sends fully-qualified hostname

### Actual Result

```
May  7 16:44:45 mailservice5 postfix/submission/smtpd[481066]: NOQUEUE: reject_warning: RCPT from vault.i-telligence.de[*.*.*.*]: 504 5.5.2 <25aea30808b2>: Helo command rejected: need fully-qualified hostname; from=<no-reply@vault.i-telligence.de> to=<*.*@i-telligence.de> proto=ESMTP helo=<25aea30808b2>
May  7 16:44:45 mailservice5 postfix/submission/smtpd[481066]: NOQUEUE: reject: RCPT from vault.i-telligence.de[*.*.*.*]: 450 4.7.1 <25aea30808b2>: Helo command rejected: Host not found; from=<no-reply@vault.i-telligence.de> to=<*.*@i-telligence.de> proto=ESMTP helo=<25aea30808b2>
May  7 16:44:45 mailservice5 postfix/submission/smtpd[481066]: lost connection after RSET from vault.i-telligence.de[*.*.*.*]
```
it make not sense to hide ipaddress here, but hey ...

### Build Version

bitwarden.sh version 2024.4.1, Docker version 24.0.5, build 24.0.5-0ubuntu1~20.04.1

### Environment

Self-Hosted

### Environment Details

Ubuntu 20.04

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
i there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration of the SMTP server or the environment variables relating to SMTP in ./bwdata/env/global.override.env.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by adminsend** [comment]
Well I dont think its a misconfigured mail service. usually it is a good idea to tighten your mail-server, an one piece of it is to inisist on a fully quallyfied domain name when using the SMTP HELO command.
While this might not be a problem while using a full-featured machine with a proper mailsystem (it usualy relies on the setting in /etc/hostname), however using a container, vaulwarden uses the containerid as hostname for itsmailconfiguration... leading to HELO rejections if you have a secured mail-service.
usually you can fix this on the mail-server site for some broken clients with using regex for whatever the come with and define an exception, but...for a randomly generated containerid this trick fails.
---
5.5.2 <e39bee85f1a8>: Helo command rejected: need fully-qualified hostname; from=<vaultwarden@xxxxx.local> to=<xxx.xxx@xxx.de> proto=ESMTP helo=<e39bee85f1a8>
---
Without having deeper knowledge about the mailinternals the vaultwarden-dockerimage is using, may i suggest to offern an environment variable where the fqdn hostname for the uses mail-layer can be given to the docker runntime? :)
