### ISSUE TITLE
Support non-interactive installs

### ISSUE THREAD

**Issue by pbostrom** [bitwarden/server#408]
This is a small issue with the run.sh script, similar to #180 in that the -t flag breaks non-interactive usage. My use case is
`# ./bitwarden.sh install < install.cfg`
where `install.cfg` has my answers for the install prompts:
```
bitwarden.mydomain.com
y
me@mydomain.com
123-456-789
aBcD1234
```
This would have no affect on the existing interactive install.

**Comment by jec** [comment]
What is the status of the above-referenced PR? I would love to be able to finish my Chef recipe that stands up a bitwarden server.

**Comment by pbostrom** [comment]
I think I'm on the hook for writing a powershell script to support Windows installs.

**Comment by djsmith85** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
