### ISSUE TITLE
Enterprise should be able to enforce 2fa of any sort, not just Duo

### ISSUE THREAD

**Issue by jikquantopian** [bitwarden/server#414]
We use a combination of Yubikeys and TOTP for 2fa within our company. We want to require all users who have access to our Bitwarden organization to use 2fa. Right now that's apparently only possible if we switch to Duo, which we're not going to do. It should be possible to configure our organization to require everyone in it to have 2fa configured and alert us about people who don't. N.B. It's not good enough to just not allow people without 2fa to access the organization, because they will still be able to access their personal vaults, which also have company credentials in them, albeit private ones. Therefore, we need Bitwarden to alert us so we can track down the people who have disabled 2fa (or never enabled it) and make them set it up.

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by kspearrin** [comment]
https://community.bitwarden.com/t/force-2fa-for-organizations/467

**Comment by mcfedr** [comment]
Hi, @kspearrin 

I'm very interested in this feature, and looking at making a PR with an implementation. 

- I'm thinking its a setting at organisation level
- The user shouldnt be able to enable the setting if he doesnt have 2FA enabled
- The org should not be accessible to any users without 2FA
- A warning message shown to the user that some items are not visible because he doesnt have 2FA enabled, and a link prompting to enable

Does this sound like a reasonable place to start from? Any pointers? Would you accept such a PR?

**Comment by kspearrin** [comment]
@mcfedr We have been planning this feature for a while now. I'd ask that you don't spend any time on it since it is corrently a priority and we plan to tackle it very soon.

**Comment by Leopere** [comment]
Is there any word on this @kspearrin ?

**Comment by ruant** [comment]
This is a **MUST** have feature in my 👀

**Comment by k158** [comment]
The lack of their feature is preventing me from rolling Bitwarden out to any more people in our organisation.  It’s a great product and I’ve been otherwise pretty happy with it.  I do think it’s important to enforce 2fa on their personal entries too given there is no way of preventing users from storing corporate content in there personal container.  Would it be so bad if everyone had to use 2fa?  We force pin security and device encryption on their mobile device and people just accept that these days.

**Comment by djsmith85** [comment]
Closing this, as enforcing 2FA for orgs was implemented. For further information please check https://bitwarden.com/help/article/policies/

**Comment by Leopere** [comment]
Yay! You rock keep up the awesome work!
