### ISSUE TITLE
Add more symbols for random password generation

### ISSUE THREAD

**Issue by leobel96** [bitwarden/server#434]
I’ve noted that random password generation, in Bitwarden, doesn’t include some symbols:

    ( { } [ ] ( ) / \ ’ " ` ~ , ; : . < > ) + | £ € ? =

Why have you excluded them? Why don’t you make random password generation “more random” adding them? You could give to the user the possibility to include or exclude these symbol as you do with other symbols.

**Comment by kspearrin** [comment]
This repo is for the server, which does not handle password generation.

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by leobel96** [comment]
I've already made [a post](https://community.bitwarden.com/t/improve-random-password-generation/4091) in feature requests about it but it has been ignored. I think it's an important feature and the forum hasn't got the same visibility of github.
