### ISSUE TITLE
Self-hosted server loses licenses on restart

### ISSUE THREAD

**Issue by oldium** [bitwarden/server#440]
I am self-hosting Bitwarden 1.28.0 on Windows 10 1809 build 17763.316, but when I restart Windows machine or it crashes, I lose licenses (both premium and also organization one). I have to re-upload them. According to [reddit thread](https://www.reddit.com/r/Bitwarden/comments/9og2kk/selfhosted_server_loses_licenses_after_machine/) I am not the only one having troubles with licenses on Windows machine restart.

There is nothing in logs which might be related, so maybe something needs to be enabled, please let me know.

The only log I see is the following in `logs/identity/Identity/20190215` (anonymized with 'x'): 
2019-02-15 07:09:23.235 +00:00 [Information] Validating premium license for user xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx("xxxxxx.xxx@gmail.com").

**Comment by kspearrin** [comment]
After researching this issue further, I have discovered that, for whatever reason, sometimes when Docker is running on Windows host machines, mapped volumes defined in the `./bwdata/docker/docker-compose.yml` file are not properly working. Meaning that any data written to the volumes is not being persisted back to the host machine and that the containers are not able to access anything from the host machine's mapped folders. The problem affects both directions.

Because of this:

1. When the license validation task runs, it cannot locate the license file located in `./bwdata/core/licenses`. It therefore, deactivates the organization since no license file is found.

2. The log messages regarding this deactivation are not written to `./bwdata/logs` since the mapping from the container to the host machine folder is also not working. This is why we have no trace of the deactivation occurring.

After I restart Docker itself, the mapping seems to start working again. I am still not sure why Docker is failing this way.

One thing I did find was the `COMPOSE_CONVERT_WINDOWS_PATHS` environment variable, as defined here:
https://docs.docker.com/compose/reference/envvars/#compose_convert_windows_paths

There is also a `COMPOSE_FORCE_WINDOWS_HOST` environment variable.

Perhaps there is an issue with pathing and Docker is getting confused sometimes. Could you try settings these environment variables on your host machine to see if it makes any difference in the issue? In my testing I have set them and have not been able to reproduce the issue since, but I am not fore sure if it's a fix yet or not.

**Comment by oldium** [comment]
Thanks for the pointers, I will try that this week.

I forgot to mention that I am currently using Docker Desktop for Windows version 2.0.2.1 (31274) from edge channel (to try if newer Docker could fix the issue).

**Comment by oldium** [comment]
No luck. I added the mentioned environment variables to system env vars with value 1 and the Bitwarden license did not survive few Windows restarts. I have to say that there was one Docker upgrade too in between and now the license has gone. I will re-apply the license and try again some restarts to catch exact point when the license is lost.

**Comment by kspearrin** [comment]
I found the following issue on docker's issue tracker the details the problem here:
https://github.com/docker/for-win/issues/584

Looks like restarting Bitwarden containers after a restart should help.

**Comment by oldium** [comment]
Thanks for the hint, but restarting after startup is out of my wanted use case. Currently I use Docker on my server (Windows 10 Pro) as a regular user, so I have to login in order to start the containers. I plan to switch to daemon mode, where the daemon is started automatically by Windows (`dockerd.exe --register-service` like mentioned in source code https://github.com/moby/moby/blob/master/cmd/dockerd/service_windows.go).

**Comment by oldium** [comment]
I am currently trying to run a docker daemon (`dockerd.exe --register-service --experimental --group docker-users`), which, as I understood, uses new [LCOW (Linux Container on Windows)](https://blog.docker.com/2018/02/docker-for-windows-18-02-with-windows-10-fall-creators-update/) technology. I had to use latest docker.exe/dockerd.exe from Git master (and download images from [linuxkit](https://github.com/linuxkit/lcow)) and tune few items in configuration, in particular:
  * config.yml:
     ```
     compose_version: 2.4
     ```
  * docker-compose.override.yml:
     ```
     version: '2.4'
     services:
       mssql:
         mem_limit: 3G
     ```
And it currently works :-) The memory constraints support for LCOW was added [recently](https://github.com/moby/moby/pull/37296) and should be part of Docker 19.03 as far as I found.

The LCOW technology does not use virtual machine as Docker Desktop does,  I did not have to configure any shared drivers. I expect that this might fix my issue with lost licenses (although new issues might arise as LCOW is a technology currently being developed).

**Comment by oldium** [comment]
The license on LCOW is kept, it survives restarts and is remembered also another day. LCOW, as it is available now without compiling anything (to be more up-to-date), is not ready for prime-time yet (containers don't recover when the PC is restarted, shutdown does not work...), but at least prove that the licensing problem is not in Bitwarden itself, but somewhere in Docker. I am closing this issue, because it looks like it is reported to the wrong project. Lets wait for LCOW, which shall really improve world of Linux containers on Windows.
