### ISSUE TITLE
port forwarding issue behind reverse proxy

### ISSUE THREAD

**Issue by RawSlugs** [bitwarden/server#442]
I setup the linuxserver io letsencrypt as reverse proxy, then when I modified the config.yml for http_port: 8080 and https_port: 5443 I get a weird port forward..

Looking at bitwarden-nginx container ports "80/TCP, 0.0.0.0:8080->8080/TCP, 0.0.0.0:5443->8443/TCP"

Where did 8443 come from?

**Comment by kspearrin** [comment]
This is the internal port nginx is running on. You are mapping 5443 to bitwarden-nginx 8443.

**Comment by RawSlugs** [comment]
Yes, I see that. But why is 5443 going to 8443 and not external and internal 5443

**Comment by kspearrin** [comment]
because 8443 is hardcoded as the internal port on the compose network.

**Comment by RawSlugs** [comment]
Oh, ok. I tried changing the port for https in config.yml to other ones and it shows successfully those ports forwarding to 8443..
If I do a nap scan on localhost whatever the port I tried to open if it's 8443, 7443 etc. Shows open.. but I still can't access through the web. So I tried a nap scan on the IP and it shows the port is closed.

Why is only the https port not opening properly? Port 8080 for http is working..

**Comment by Hinton** [comment]
This sounds like a configuration issue outside of the Bitwarden server. We use GitHub to track issues in the software, if this is still an issue, we kindly as that you contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
