### ISSUE TITLE
Accept ALL Types of Certs, or how to get a Cert on another Port

### ISSUE THREAD

**Issue by geheimnisvollriesigernasenbaer032** [bitwarden/server#449]
Hello!
and first sorry for my english! I try my best.

I have following Problem: I have a Server at Home. With Proxmox on that and with many VM's. For every Service one. OPNsense, Openmediavault, Plex, Bitwarden, and many others. All have own VM. 

i have a XYZname.myqnapcloud.com domain. 

I installed Bitwarden like described (https://help.bitwarden.com/article/install-on-premise/). Everything worked with self generated cert. But since last Update from Firefox, it doesnt accept anymore any self generated Certs. And there is now way to ignore that (i tryed already everything, yes everything!). 

Now i want to install bitwarden with a valid cert. So i delete the Bitwarden VM, created new one. Installed Debian on it and everything else. But i cant get Bitwarden to install successfully. Because i cant use Port 80 and 443 because these ports already used from the Qnap NAS. And i cant and i dont want to change the Ports from the NAS. 

And there is no Way at the Installation to choose another Ports. Why not? 

I want to use Port 8080 and 8443. Knows anybody how to? Thanks.

**Comment by djsmith85** [comment]
Hi @geheimnisvollriesigernasenbaer032 I know this is a very old issue, but just in case you still need the info: Please have a look here: https://github.com/bitwarden/server/issues/436

Thanks for getting in touch! We use GitHub issues as a place to track bugs and other development related issues. If you'd like help using or configuring Bitwarden, please contact our Customer Success team here: https://bitwarden.com/contact. You can include a link to this issue in the message content. You can also search for an answer in our [help documentation](https://bitwarden.com/help/) or get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/). The issue here will be closed.
