### ISSUE TITLE
DOC - Server Setup Guide

### ISSUE THREAD

**Issue by Herz3h** [bitwarden/server#4559]
### Steps To Reproduce

Not sure if this issue belong here but here it is:

In this section https://contributing.bitwarden.com/getting-started/server/guide#azurite it doesn't say that one should start the storage service (azurite) before running `pwsh setup_azurite.ps1`

### Expected Result

Should give a step to start azurite service

### Actual Result

Running `pwsh setup_azurite.ps1` will just keep looping since azurite server is not started.

### Build Version

Latest

### Environment

Cloud (bitwarden.com)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there, 

This is not a bug, but rather a documentation issue. 

You can edit the page if you scroll right down and click on "edit page"

![image](https://github.com/user-attachments/assets/fa3579ac-9314-4e8c-bc64-e8439b756c64)

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
