### ISSUE TITLE
User's can't log in with SSO suddenly: The absolute expiration value must be in the future.

### ISSUE THREAD

**Issue by FGSD15** [bitwarden/server#4576]
### Steps To Reproduce

Owners can log in just fine.

But if a user needs to log in:
They enter their email address.
Click on Enterprise single sign-on
Enter their SSO identifier

It them comes up with this new error:
Window has the title: Error - SSO
The page has:
Error
There was an unexpected error during single sign-on.

The absolute expiration value must be in the future.
Request ID:  <then a string of 55 characters> in the format: nn-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxxxxxx-nn
© 2024, Bitwarden Inc.
Version 2024.7.3

### Expected Result

Should kick off to SSO but it's not

### Actual Result

User cna't log in

### Githash Version

85ddd080-dirty

### Environment Details

Container running version: bitwarden/self-host:beta
Web page is showing it as version 2024.7.1

### Database Image

Mariadb container running version: 11.4.2-MariaDB-ubu2404

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment]
Hi there,

Thank you for your report! I think your error could have its origin in a misconfiguration of your setup.

If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by FGSD15** [comment]
It was working perfectly fine on beta 6.2, but I tried reverting back to that version, and while it runs, it then doesn't let anyone log in (not even owners)

**Comment by FGSD15** [comment]
The resolution to this issue was the time zone in the Bitwarden Unified container cannot be set to the local time zone. It has to explicitly be set to UTC (this doesn't appear to be in the documentation btw).
