### ISSUE TITLE
New Device Logged Notification - local IP

### ISSUE THREAD

**Issue by DevTek314** [bitwarden/server#463]
When I connect to Bitwarden with a new device, only the local Docker IP is displayed in the email.

![image](https://user-images.githubusercontent.com/6564899/54825350-9d159000-4cad-11e9-89ff-d9329db20656.png)

**Comment by kspearrin** [comment]
This is an issue with Docker. See https://github.com/docker/for-mac/issues/180

**Comment by karelvanhecke** [comment]
@kspearrin

I actually believe that's not the issue.

"When processed, X-Forwarded-{For|Proto|Host} values are moved to X-Original-{For|Proto|Host}.

If there are multiple values in a given header, note Forwarded Headers Middleware processes headers in reverse order from right to left.

The default ForwardLimit is 1 (one), so only the rightmost value from the headers is processed unless the value of ForwardLimit is increased." - from https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-2.2


The X-Forwarded-For field contains the client IP followed by all proxies.

For example:

`X-Forwarded-For: client, proxy1, proxy2`

If it is processed the way it is described above, all self-hosted instances will always get the proxy IP, in this case the NGINX Docker container, instead of the actual client IP. Even if there's only one proxy.

So unless a higher ForwardLimit is set or a workaround similar to what you used to get the real client IP address from Cloudflare, is used (in this case the leftmost value of the header "X-Forwarded-For" should suffice), people with a self-hosted Bitwarden instance are always going to have the wrong client IP address.

**Comment by kspearrin** [comment]
@karelvanhecke You mentioned in your PR that this solution works for you. Unfortunately, that doesn't seem to be the case in all situations since it would not work on my test installation. I don't see the real client IP anywhere in the headers from `domain.com/api/ip`. So what is different about your setup? You said you are using a reverse proxy?

**Comment by karelvanhecke** [comment]
@kspearrin I have another NGINX reverse proxy acting as a WAF in front of my Bitwarden deployment. I've checked some other setups that I could find on shodan.io and it seems that those who also deploy an additional reverse proxy have the same results as me.

**Comment by karelvanhecke** [comment]
@kspearrin I just spun up a new Bitwarden instance to verify this (Docker CE on Centos 7). X-Forwarded-For and X-Real-IP (since there is only one reverse proxy) both contain the correct client IP. Using my workaround to extract the correct client IP address from X-Forwarded-For should work for all instances (even Bitwarden's own hosted service behind CloudFlare).
May I ask on what platform your test environment is setup on?

**Comment by kspearrin** [comment]
@karelvanhecke I have a standard installation on localhost with Ubuntu 18 here. This is what I see:

```
{
  "Ip": "::ffff:172.23.0.2",
  "Headers": {
    "Cache-Control": [
      "max-age=0"
    ],
    "Connection": [
      "close"
    ],
    "Accept": [
      "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
    ],
    "Accept-Encoding": [
      "gzip, deflate, br"
    ],
    "Accept-Language": [
      "en-US,en;q=0.5"
    ],
    "Host": [
      "localhost"
    ],
    "User-Agent": [
      "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0"
    ],
    "X-Real-IP": [
      "172.23.0.1"
    ],
    "X-Forwarded-For": [
      "172.23.0.1"
    ],
    "X-Url-Scheme": [
      "https"
    ],
    "X-Forwarded-Proto": [
      "https"
    ],
    "upgrade-insecure-requests": [
      "1"
    ]
  }
}
```

**Comment by karelvanhecke** [comment]
@kspearrin 
The only time I can't reproduce the correct results is when accessing Bitwarden from localhost.
 Accessing Bitwarden from a remote machine (even with a standard installation) should always give the correct client IP address in X-Forwarded-For.
In a production environment, Bitwarden would never be accessed from localhost, so that shouldn't be a problem.

There does appear to be an issue with docker, but one that shouldn't affect production environments.

**Comment by kspearrin** [comment]
I also tested this on my Windows workstation with a regular subdomain open to the internet. It doesn't work there either:

```
{
  "Ip": "::ffff:172.18.0.10",
  "Headers": {
    "Cache-Control": [
      "max-age=0"
    ],
    "Connection": [
      "close"
    ],
    "Accept": [
      "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
    ],
    "Accept-Encoding": [
      "gzip, deflate, br"
    ],
    "Accept-Language": [
      "en-US,en;q=0.5"
    ],
    "Cookie": [
      "__cfduid=dd5062642057b3482ab82e0e47e9718751541798514"
    ],
    "Host": [
      "bw.kylespearrin.com"
    ],
    "User-Agent": [
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0"
    ],
    "X-Real-IP": [
      "172.18.0.1"
    ],
    "X-Forwarded-For": [
      "172.18.0.1"
    ],
    "X-Url-Scheme": [
      "https"
    ],
    "X-Forwarded-Proto": [
      "https"
    ],
    "upgrade-insecure-requests": [
      "1"
    ]
  }
}
```

Not sure why it works for you.

**Comment by karelvanhecke** [comment]
```
{
  "Ip": "::ffff:172.18.0.10",
  "Headers": {
    "Connection": [
      "close"
    ],
    "Accept": [
      "*\/*"
    ],
    "Host": [
      "bitwarden.domain.com"
    ],
    "User-Agent": [
      "curl\/7.29.0"
    ],
    "X-Real-IP": [
      "10.0.60.10"
    ],
    "X-Forwarded-For": [
      "10.0.60.10"
    ],
    "X-Url-Scheme": [
      "https"
    ],
    "X-Forwarded-Proto": [
      "https"
    ]
  }
}
```

This is the result I'm getting when accessing my Bitwarden instance directly and bypassing my WAF. Which contains the expected client IP address.

**Comment by kspearrin** [comment]
The only winning combination seems to be a Linux host on non-localhost public domain.

**Comment by c4539** [comment]
With the latest version, it's a bit better (IPv4 is displayed as IPv4), but still, if you run BW behind a proxy (e.g. Apache or another nginx), you will see the proxy's IP address (it's basically the gateway in the docker network).

I guess it's due to this configuration in Bitwarden's nginx proxy.conf:

```
proxy_set_header X-Real-IP $remote_addr;
```

Any chance we can make this configurable?

**Comment by karelvanhecke** [comment]
@c4539 You need to set your reverse proxy IP in config.yml.

**Comment by c4539** [comment]
> @c4539 You need to set your reverse proxy IP in config.yml.

Looks like I missed that configuration. Thanks.

**Comment by DevTek314** [comment]
It's working now.
