### ISSUE TITLE
Still binding on port 80?

### ISSUE THREAD

**Issue by deanfourie1** [bitwarden/server#4641]
### Steps To Reproduce

1. Replace port 80 with another port in the docker-compose.yml file
2. Replace port 80 with another port in the bwdata/config.yml
3. start all containers
4. Check port bindings in docker, still bound to port 80.

### Expected Result

For the container to run on the specified ports.

### Actual Result

Container still binds on port 80, as well as the other ports specified.

### Build Version

2024.7.3

### Environment

Self-Hosted

### Environment Details

- Docker compose on Debian 12 Proxmox VM

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment]
hello @deanfourie1 

I think your issue/ error could have its origin in a misconfiguration. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.
