### ISSUE TITLE
Own SSL certificates

### ISSUE THREAD

**Issue by SandraCCH** [bitwarden/server#471]
Givs a change to use my own ssl certificates? I found many informations, but nothing run.

My certificates are on a NFS Share. How can i get the share for the Docker?

**Comment by kspearrin** [comment]
Please the certificates in `./bwdata/ssl` and then map them in the `./bwdata/config.yml` file.

**Comment by SandraCCH** [comment]
Thank you. But Givs a change to Use the NFS share?
I search a silution to Use the share witheout copy the files

**Comment by jult** [comment]
I agree, this silly docker requirement is ruining a perfectly fine opportunity to use our own certs. Why not create a decent apt package for debian servers? Just note the added points of failure and security risks opened up by using a docker for selfhosted bitwarden servers.

**Comment by JohnGalt1717** [comment]
For anyone that finds this here's how you make it work:
bitwarden stop
Delete everything in your letsencrypt folder if you had it running before.
open your config.yml file
ssl_managed_lets_encrypt: false
ssl_certificate_path: /etc/ssl/<full chain file>
ssl_key_path: /etc/ssl/<key file>
ssl_ca_path: /etc/ssl/<ca file>
ssl_diffie_hellman_path: /etc/ssl/<dh file if needed>

Note the root pathing to make it work. Otherwise you're in the /etc/ngix folder not the right one as claimed by the docs.

Also note that you can't use symbolic links because of an issue with docker.  It would be nice if the script took those file paths and did a full mapping because if you use your own lets encrypt instead of the built in one, all of the files are symbolic links so in docker you have to map the full path with the file name, not just the folder that contains the files otherwise it won't work. The work around is to copy the files out of the folder and into another one so they're no longer symbolic links.
