### ISSUE TITLE
Possible to configure oidc settings via the helm chart?

### ISSUE THREAD

**Issue by lknite** [bitwarden/server#5062]
### Steps To Reproduce

.

### Expected Result

.

### Actual Result

.

### Screenshots or Videos

.

### Additional Context

.

### Build Version

.

### Environment

Self-Hosted

### Environment Details

.

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development related issues. To receive support, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
