### ISSUE TITLE
[Suggestion] Identity Generator

### ISSUE THREAD

**Issue by Yeehawlerz101** [bitwarden/server#524]
Didn't know where I'd paste this. If we can generate a Identity and use it as a folder to store contents as that identify.
Tl;dr
* Use Identities as folder
* Generate identity data as template data for auto fill.

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
