### ISSUE TITLE
docker: open /data/bwdata/env/uid.env: no such file or directory.

### ISSUE THREAD

**Issue by icekingcy** [bitwarden/server#550]
root@XXXXXXX:/data# ./bitwarden.sh install
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2019, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

Docker version 18.06.1-ce, build e68fc7a
docker-compose version 1.22.0, build unknown

(!) Enter the domain name for your Bitwarden instance (ex. bitwarden.example.com): XXXXXXX

(!) Do you want to use Let's Encrypt to generate a free SSL certificate? (y/n): n

1.31.1: Pulling from bitwarden/setup
Digest: sha256:846d5c1fd83dc00f0bd2994c1a6f0cea4d246200a7311e01f3bf103078b92a92
Status: Image is up to date for bitwarden/setup:1.31.1
docker: open /data/bwdata/env/uid.env: no such file or directory.
See 'docker run --help'.

**Comment by Rainson12** [comment]
i run into the same issue

**Comment by andriimakarenko** [comment]
@icekingcy @Rainson12 do you use Ubuntu Server for this?
Since the file is actually there, it seems like some permission issue. Please reproduce it check the output of the following command:
`dmesg -T | grep docker`

Is there anything that looks something like this?
`[Sat May  1 07:18:49 2021] audit: type=1400 audit(1619853530.627:39): apparmor="DENIED" operation="open" profile="snap.docker.compose" name="/proc/2016/mounts" pid=2016 comm="python3" requested_mask="r" denied_mask="r" fsuid=0 ouid=0`

If yes, this might be the cause of your issue
