### ISSUE TITLE
"Unable to validate installation ID"

### ISSUE THREAD

**Issue by dan-christensen** [bitwarden/server#595]
I'm getting this error:

```

Open source password management solutions
Copyright 2015-2019, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

Docker version 19.03.4, build 9013bf583a
docker-compose version 1.24.1, build 4667896b

(!) Enter the domain name for your Bitwarden instance (ex. bitwarden.example.com): <snip>

(!) Do you want to use Let's Encrypt to generate a free SSL certificate? (y/n): n

1.32.0: Pulling from bitwarden/setup
Digest: sha256:e88f1611ff88c77a6255c49189ac3c965aaa3576fa6980ba54f2be10a96907b5
Status: Image is up to date for bitwarden/setup:1.32.0
docker.io/bitwarden/setup:1.32.0

(!) Enter your installation id (get at https://bitwarden.com/host): <snip>

(!) Enter your installation key: <snip>

Unable to validate installation id. Problem contacting Bitwarden server.

```
When I try to ping https://api.bitwarden.com/installations + <install-Id> I get a return object, so I think my docker container is having trouble accessing the internet.

**Comment by kspearrin** [comment]
I would try bashing into a docker container and doing the same test.

**Comment by dan-christensen** [comment]
Is this what you mean?
```
nobody@53eced071a04:/app$ curl https://api.bitwarden.com/installations/<snip>
curl: (6) Could not resolve host: api.bitwarden.com
nobody@53eced071a04:/app$ 
```

**Comment by kspearrin** [comment]
Seems right. Can you curl any endpoint? If not, you probably have some networking issue you need to figure out.

**Comment by dan-christensen** [comment]
No I can't. I'm pretty new to docker? How would I do that?

**Comment by kspearrin** [comment]
Do you have any firewalls or anything that are limiting access?

**Comment by dan-christensen** [comment]
No I don't believe so. I've opened port 80 and 443.

**Comment by dan-christensen** [comment]
Fixed. The docker internet connection was down. I enabled 'connect automatically' in cockpit.

**Comment by 3nuc** [comment]
I find it confusing that there are no "how to troubleshoot bitwarden.sh install" instructions anywhere.
To do what kspearrin says above ...:
>Seems right. Can you curl any endpoint? If not, you probably have some networking issue you need to figure out.
and infact see that `curl api.bitwarden.com/installations/[installation-id]` doesn't work for you, you need to run `docker run` in a special way, because just `docker run [image id]` will just make the image shutdown after a few seconds.

Try this:
Find the id of the bitwarden setup container:
```sh
artur@debian:~$ docker image ls
bitwarden/setup                        latest               d848af68640b   3 weeks ago     281MB
```

Run the container in a special "doesn't die after 5 seconds mode":
```
docker run -d d848af68640b tail -f /dev/null
```

After that, the container should be alive:
```
artur@debian:~$ docker container ls
CONTAINER ID   IMAGE                             COMMAND                  CREATED              STATUS                   PORTS                                                                                       NAMES
da77f9d6b209   d848af68640b                      "/entrypoint.sh tail…"   About a minute ago   Up About a minute                                                                                                    charming_keldysh
```

So we can "ssh" into it:
```
docker exec -it da77f9d6b209 /bin/bash
```

And see that infact curl fails:
```
root@da77f9d6b209:/app# curl api.bitwarden.com/installations/[installation-id]
curl: (6) Could not resolve host: api.bitwarden.com
```

**Comment by 3nuc** [comment]
Fixed it. 

Basically, this is caused by a generic "docker container can't access the internet" problem that has happened to every Docker user ever at least once. You can make sure that you infact can't access the internet from inside ./bitwarden.sh by doing the steps I've provided above (curl should fail)

In my case:
* I was using nftables on my server
* I rolled back to using iptables
* but I forgot to remove --iptables=false from /etc/systemd/system/docker.service (so doing the opposite of what this tutorial says https://linuxconfig.org/how-to-disable-docker-s-iptables-on-systemd-linux-systems)

After removing --iptables=false and restarting the docker service, ./bitwarden install validates the installation id correctly
