### ISSUE TITLE
Two step verification disabled when recover from a backup (Self-hosted)

### ISSUE THREAD

**Issue by arthurire** [bitwarden/server#635]
I only have two Yubikeys for 2 step verification(YubiKey OTP). After recover from my previous backup(I migrated my installation from one machine to another), my premium account license is missing and two step verification is disabled.

I'm sure I followed the backup instruction and configurations related to 2 step verification are included in my backup. Because once I uploaded my premium license after migration, those two yubikeys are correctly configured.

So, it seems that once my premium account expired (in my example, I lost this license during migration), premium functions are disabled including YubiKey OTP, which means my 2 step verifications are invalid (Again, this is my only 2 step verification method).

My question is:

1. Is there something wrong with my backup which makes me lost my license?

2. Is this a bug? "When no available 2 step verification method exists, disable 2 step verification and you can login ONLY with your password."

**Comment by naufalirfan** [comment]
For question 2 i think it's not a bug, if no 2 step method and you can't login only with password, it mean you lost access to your account permanently. if 2 step not exist then only need password, it's already correct.

The problem is in 2 step verification removal. I think it should not remove the 2 step even if license didn't exist. I know YubiKey OTP is premium feature, so remove it but make it unusable so user required to deactive/reset 2 step using Recovery Code or re-enable license.

**Comment by arthurire** [comment]
> For question 2 i think it's not a bug, if no 2 step method and you can't login only with password, it mean you lost access to your account permanently. if 2 step not exist then only need password, it's already correct.
> 
> The problem is in 2 step verification removal. I think it should not remove the 2 step even if license didn't exist. I know YubiKey OTP is premium feature, so remove it by make it unusable forcing user to deactive/reset 2 step safely using Recovery Code or re-enable license.

Agree with you.

I mean at least it should require my Yubikey and then force me to add a two-step verification method or cancel it.
