### ISSUE TITLE
Office 365 is categorizing all Bitwarden emails as a phishing attempt

### ISSUE THREAD

**Issue by Mart124** [bitwarden/server#636]
Hi,

Relaying this here :
https://community.bitwarden.com/t/office-365-is-categorizing-all-bitwarden-emails-as-a-phishing-attempt/9761

Since a few days, Office 365 users do not receive Bitwarden mails anymore.
Mails are even not available in SPAM box.
Of course it used to work perfectly.
A tricky situation, especially in companies using Office 365 !

Could we dig into this ?
Many thx 👍

**Comment by sevensixseven** [comment]
Currently, Microsoft is marking some of our emails as possible phishing messages. We have reported this to Microsoft and are waiting on a response. In the meantime, please check your Quarantine. https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/find-and-release-quarantined-messages-as-a-user 

You may want to add a rule to your Quarantine settings to allow emails from bitwarden.com until the issue is resolved.

**Comment by CSAS-Nicholas-Roberts** [comment]
This issue seems to be affecting users with Exchange Online Protection as well. Unfortunately that system does not allow the same type of quarantine control as Office 365 does, meaning that you can't change quarantine settings to allow emails from bitwarden.com. 

The only way around it in this case was to try to log in, hit 2FA, check the quarantine and release the email when it arrives, get logged in and then update the 2FA method / email address to alleviate the issue until this is resolved. Hopefully this helps someone else racking their brain in the meantime.

**Comment by Mart124** [comment]
Do you all still face this issue ?
Did you managed to get a response from Microsoft ?
If OK now I'll close this ticket.
Thx 👍

**Comment by CSAS-Nicholas-Roberts** [comment]
@Mart124 I had changed over to a different 2FA method after these issues. I'll switch back, do some test, and then get back soon!

**Comment by CSAS-Nicholas-Roberts** [comment]
@Mart124 Looks like it is working again.
