### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by dusatvoj** [bitwarden/server#665]
Hi,
I want to deploy bitwarden server. But I have docker server behind firewall and NAT (with local IP only). And I have Apache2 reverse proxy server.
How can I deploy bitwarden to this infrastructure?
Actual behavior is that nginx is keep restarting.
Thank you

**Comment by kspearrin** [comment]
You need to figure out why your nginx container is restarting. Run `docker logs bitwarden-nginx`

**Comment by dusatvoj** [comment]
Nginx have a problem with non-existing certificate but I don't want HTTPS between bitwarden nginx and apache hosting.

**Comment by kspearrin** [comment]
You can remove any cert configuration from ./bwdata/config.yml and run a rebuild.

**Comment by demolisherBR** [comment]
Hi. I believe the nginx container keeps restarting because of the following errors:
_chown: cannot access '/etc/bitwarden': No such file or directory
cp: cannot stat '/etc/bitwarden/nginx/default.conf': No such file or directory
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
2020/03/31 20:40:29 [emerg] 1#1: open() "/var/log/nginx/error.log" failed (13: Permission denied)_

Got these errors trying to run the container alone with docker run
