### ISSUE TITLE
Cloudflare Forever Loading - CSP Block

### ISSUE THREAD

**Issue by shrunbr** [bitwarden/server#713]
While using Bitwarden behind Cloudflare I'm receiving a "forever load".

![image](https://user-images.githubusercontent.com/13515931/80328551-46aa4780-8805-11ea-9394-d4f4a09dd0e2.png)

After a bit of investigation I found that Cloudflare rocketloader scripts were being blocked by CSP within bitwarden-nginx in /etc/nginx/conf.d/default.conf.

![image](https://user-images.githubusercontent.com/13515931/80328628-75c0b900-8805-11ea-96bb-09b5cf0c955f.png)
![image](https://user-images.githubusercontent.com/13515931/80328648-8a04b600-8805-11ea-8d8b-6c9ad8ec515c.png)

EDIT: I was able to get this resolved by adding `script-src 'self' https://ajax.cloudflare.com;` to the end of the content security policy in bwdata/nginx/default.conf and restarting the bitwarden-nginx container.

EDIT2: Link to using CSP w/ Cloudflare: https://support.cloudflare.com/hc/en-us/articles/216537517-What-is-Content-Security-Policy-CSP-and-how-can-I-use-it-with-Cloudflare-

**Comment by shrunbr** [comment]
This may also be related to #503

**Comment by darkrain-nl** [comment]
Isn't there a way to make this configurable?
I don't want to add this to my self hosted non Cloudflare instance...

**Comment by Hinton** [comment]
It's possible to configure the CSP policies, https://github.com/bitwarden/server/blob/master/util/Setup/Configuration.cs#L81.

In case you still need assistance configuring this, please contact our Customer Success team here: https://bitwarden.com/contact. You can include a link to this issue in the message content. You can also search for an answer in our [help documentation](https://bitwarden.com/help/) or get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/). The issue here will be closed.
