### ISSUE TITLE
Too many redirects on ubuntu 18,04

### ISSUE THREAD

**Issue by XXXAUTISTIC** [bitwarden/server#735]
Hello, I'm afraid I have a problem with Bitwarden right now.

After several attempts, the installation has finally worked, but Bitwarden now tells me that I am getting 
too many redirects. I have found nothing in google regarding this, can anyone help me?

I followed this tutorial to install it: https://golb.hplar.ch/2018/12/self-host-bitwarden.html
Here is my config.yml (i disabled https cuz it doesnt work with it enabled): https://hastebin.com/otenewiyay.shell

**Comment by SamarthH** [comment]
If you are dual booting and have just shifted from Windows to Ubuntu, this would usually happen due to your clock not being synchronised with the server time/ actual time in your timezone. To correct for that, try [http://ubuntuhandbook.org/index.php/2016/05/time-differences-ubuntu-1604-windows-10/](url)

**Comment by djsmith85** [comment]
Hi @XXXAUTISTIC , it looks like there is a viable workaround or resolution for the issue you're experiencing. Please let us know if this resolves the originally posted issue.
