### ISSUE TITLE
Disconnect / Session expired immediatly after login

### ISSUE THREAD

**Issue by schneiderolivier** [bitwarden/server#739]
Hello,
I just install Bitwarden with docker images.
And when i connect with a user just created, i receive the error "Disconnect / Your session has expired".
With google chrome dev tools, i get the following error:
Request URL: https://myserver/api/sync?excludeDomains=true 
Error Code 401
Bearer error="invalid_token"

Plese help.

Thank you

**Comment by schneiderolivier** [comment]
A precision. I have the following error from API logs.
2020-05-19 09:59:29.986 +00:00 [Error] Exception occurred while processing message.
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'http://identity:5000/.well-known/openid-configuration'.
 ---> System.IO.IOException: IDX20807: Unable to retrieve document from: 'http://identity:5000/.well-known/openid-configuration'. HttpResponseMessage: 'StatusCode: 404, ReasonPhrase: 'Not Found', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:

Regards,

**Comment by kspearrin** [comment]
It appears that your API server cannot contact the identity server. Are they on the same docker network?

**Comment by schneiderolivier** [comment]
Yes all docker images are on the same server, a ubuntu distribution.
![image](https://user-images.githubusercontent.com/65603405/82349623-a3f77a00-99fa-11ea-96c2-8b3efbc8d3bd.png)

**Comment by kspearrin** [comment]
You have a few unhealthy containers. Can you run `docker logs ....` command to see what the issues are.

**Comment by schneiderolivier** [comment]
Yes. I saw this but docker logs show no errors for the three containers

**Comment by klepptor** [comment]
@schneiderolivier 

could you solve your problem?

I'm having the same issue on two different fresh installed Debian 10 VMs using Docker.

[nginx_access.log](https://github.com/bitwarden/server/files/4971728/nginx_access.log)
[nginx_error.log](https://github.com/bitwarden/server/files/4971729/nginx_error.log)

Except nginx all my containers are unhealty!?!?

![grafik](https://user-images.githubusercontent.com/3921511/88387530-efd7ee00-cdb2-11ea-9d53-d04ee761dc17.png)

**Comment by klepptor** [comment]
@schneiderolivier 

We just solved at least our problems:

The user starting bitwarden.sh needs to be root, it's not sufficient, if he the right to execute docker. If it's not root, you can install Bitwarden, but all containers are unhealthy --> you can't login, session expires immediatly!

Furthermore you have to make sure, Bitwarden can access the identity container without the proxy, otherwise you get api failures in the logs.

/root/.docker/config.json
```
{
 "proxies":
 {
   "default":
   {
     "httpProxy": "http://proxy.local:8080",
     "httpsProxy": "http://proxy.local:8080"
     **"noProxy": "identity"**
   }
 }
}
```


@kspearrin This is kind of odd. There is no hint in the docs (at least I can't fin it) that you have to use a root account to deploy bitwarden!

**Comment by kspearrin** [comment]
`root` is not required to deploy Bitwarden, and is actually discouraged. The user does need to be able to execute docker containers, however.

**Comment by klepptor** [comment]
At least in my case, 3 Debian VMs with Docker 19.03.12 and docker-compose 1.26, 2 of them behind a proxy, it simply doesn't work when the user starting Bitwarden is not root. The "normal" user has the right to use docker and can start other containers (and bitwarden, where the container become unhealthy).

But I just checked it with Ubuntu 16.04, Docker 19.03.12 and docker-compose 1.25.5. On this maschine it works without root and I can login, althought all containers are unhealthy, too. Now I'm totally confused!

![grafik](https://user-images.githubusercontent.com/3921511/89300276-3c9bae80-d668-11ea-8d0f-41802ce2ce51.png)

**Comment by klepptor** [comment]
@kspearrin Sorry, of course you are right. **root** is NOT required!
I messed up the proxy settings for different users on my VMs! :-(

It's all about ~/.docker/config.json 

But I'm still confused about the noProxy setting for the identity container...

**Comment by msusta** [comment]
@klepptor The thing is that once you setup a HTTP_PROXY variable - every connection is tried through the proxy. Only the hostnames specified in the NO_PROXY variable will be done directly.

Some of the bitwarden containers need to talk between each other and they have to do it directly, instead of going through the proxy - hence the exception for the identity service to be reachable from other containers.

This would have been a great addition to documentation, really.
