### ISSUE TITLE
MySQL comatibility! NOW!

### ISSUE THREAD

**Issue by Spacelord09** [bitwarden/server#806]
I will speak for several users here when I say that you should finally get away from mssql and support custom MySQL, MariaDB and Postgres installations.

my opinion is that an "open source" project should not be forced to use a specific proprietary database server software.

**Comment by kspearrin** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!

**Comment by Spacelord09** [comment]
Rly? And whats that? https://github.com/bitwarden/server/issues/453

**Comment by Spacelord09** [comment]
Im reopening this for now ;)

**Comment by Spacelord09** [comment]
@kspearrin I think you need to reopen that Issue ;)

**Comment by tgreer-bw** [comment]
@Spacelord09 here's the forum post that we're tracking for this:
https://community.bitwarden.com/t/use-other-database-than-mssql/612

**Comment by Spacelord09** [comment]
@tgreer-bw Are there any news about the forum post?
