### ISSUE TITLE
Cannot login Says unknown error occured

### ISSUE THREAD

**Issue by insaaniManav** [bitwarden/server#845]
Hi Bitwarden team, 
First of all thank you for working on and maintaining this awesome password management tool. You guys rock !
# The problem 
I recently tried deploying bitwarden on a server with a reverse proxy and nginx. The website loads just fine and lets me create a user but as soon as I try to login it tells me that an unknown error occured  and doesn't let me login 
# The logs 
2020-08-02 04:24:45.331 +00:00 [Information] Identity started.
2020-08-02 04:25:12.077 +00:00 [Error] No client with id "name here" found. aborting
These are from logs/identity/Identity . Could not find any other logs 
# Reproduce this
As I have mentioned before This is running behind reverse nginx proxy and we are using our own letsencrypt configuration for the same . I have changed the directory paths to the certificates in the config file 

Looking forward to hearing back,
Manav

**Comment by kspearrin** [comment]
> No client with id "name here" found. aborting

Does it actually say "name here" or did you change that?

**Comment by insaaniManav** [comment]
Nope I changed that it used to have username

**Comment by kspearrin** [comment]
What kind of username? Was it the email address of the person logging in?

**Comment by stelucz** [comment]
Hi!
I have same/similar problem. I deployed 1.35.1 week ago and it was running fine. Yesterday, I started new containers with latest version by commands (manual on-site deployment because I did not want to use included nginx container):
```
docker-compose pull
docker-compose run -d
```
After these steps I can not log in with message "An error has occurred. An unexpected error has occurred."

Only error message which I found is following:
```
<omitted>
2020-08-05 08:43:26.80 spid6s      Starting up database 'master'.
ForceFlush feature is enabled for log durability.
2020-08-05 08:43:27.33 spid6s      Service Master Key could not be decrypted using one of its encryptions. See sys.key_encryptions for details.
2020-08-05 08:43:27.34 spid6s      An error occurred during Service Master Key initialization. SQLErrorCode=33095, State=8, LastOsError=0.
2020-08-05 08:43:27.46 spid6s      SQL Server Audit is starting the audits. This is an informational message. No user action is required.
<omitted>
```
I tried to run 1.35.1 image of mssql back again but did not resolved the problem.

Any help appreciated. Thanks.

**Comment by insaaniManav** [comment]
> What kind of username? Was it the email address of the person logging in?

Yes it name of the person logging in

**Comment by xracrossx** [comment]
I'm having a similar issue. I have been self-hosting Bitwarden since February. Since the latest version I cannot login from the webserver or through browser extension, "An error has occurred. An unexpected error has occurred." My bwdata/logs/identity/Identity/log.txt reads as follows:

`2020-09-19 02:11:35.305 +00:00 [Error] Invalid client configuration for client "browser": "AllowedCorsOrigins contains invalid origin: https://bitwarden.FQDN.net/"
2020-09-19 02:11:35.306 +00:00 [Error] No client with id '"browser"' found. aborting
2020-09-19 02:16:19.790 +00:00 [Error] Invalid client configuration for client "web": "AllowedCorsOrigins contains invalid origin: https://bitwarden.FQDN.net/"
2020-09-19 02:16:19.791 +00:00 [Error] No client with id '"web"' found. aborting`

My FQDN has been changed to protect the innocent. These entries occur in the log for each time I fail to login. I appear to be able to login successfully from the Windows PC Application as well as the iPhone app. I am using nginx reverse proxy and a letsencrypt ssl certificate.

I would appreciate any insight or assistance, thanks for your time.

**Comment by kspearrin** [comment]
@xracrossx Looks like a CORS issue. Make sure your base service URIs under bwdata/env/global are correct.

**Comment by xracrossx** [comment]
@kspearrin Thank you my problem appears to be solved simply by changing

>globalSettings__baseServiceUri__vault=https://bitwarden.FQDN.net/

to

>globalSettings__baseServiceUri__vault=https://bitwarden.FQDN.net

(dropped the trailing slash)

**Comment by clayadams5226** [comment]
@insaaniManav are you still having this issue? We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.

**Comment by thstarshine** [comment]
This is an old post, but just wanna share some personal findings regarding this issue:

If you self-host the bitwarden service behind a proxy (like Nginx) and use an `auth_basic` rule to protect the route, when you send the login request, the `Authentication` header will also be sent to the identity server. I think this somehow confuses the identity server and it will try to set the `client_id` to the username of the `Authentication` header.

So, just remove anything that will add the `Authentication` header to your HTTP request and it will be fine.
