### ISSUE TITLE
API calling api/public/groups broken field.

### ISSUE THREAD

**Issue by alexacallmebaka** [bitwarden/server#852]
Whenever I submit a GET request to the api/public/groups endpoint, the "collections" field for each group returns "None" on every group, even if they have access to collections. I can verify that these groups have access to collections by sending a GET request to the  api/public/collections endpoint as the "groups" field returns as expected on each collection. I have tried to make this request with both the Python requests module as well as Postman. I am making calls to a self-hosted Bitwarden instance.

**Comment by cscharf** [comment]
Thanks @alexacallmebaka , looks like you found a "todo" in our public API implementation, https://github.com/bitwarden/server/blob/master/src/Api/Public/Controllers/GroupsController.cs#L90

We'll get this on our backlog.

**Comment by AqeelAT** [comment]
Is anyone working on this? If not, I'd love to do it.

**Comment by cscharf** [comment]
@AqeelAT , no one is assigned yet, if you would like to tackle this please feel free (and thank you!)

**Comment by DavidSSL** [comment]
Is there any documentation about the development process? I was able to find the swagger endpoint but then I'm required to authorize the requests for which I need a client_id and secret. Where can I find these credentials for development purposes? Is it somewhere in the Identity project?

**Comment by cscharf** [comment]
Hi @DavidSSL , for local development (getting community development guides published is on our radar), here are some excerpts from our internal development wiki:

# Local Development: Server
For local development and running the Server (Api, Identity, etc.) you'll need to setup a few things in order to make that work, connect to your own local SQL instance (docker image), as well as have appropriate certificates available for doing encrypty type things.

## User Secrets
You will need to manage user secrets for each site project in the Server solution. This includes predominately the Api and Identity projects, although there are other, lessor used ones that may also need it depending on what you're doing, but these 2 set the foundation.

### Visual Studio on Windows
You can simply right-click on the Project and "View User Secrets" (or something like that), easy peasy.

### Visual Studio on macOS
You must open a terminal and go to each project directory. Once there you initiate and create the blank user secrets file by running,

```bash
dotnet user-secrets init
```

You can then view/list any secrets you have set by running, `dotnet user-secrets list`. For more info see: [Safe storage of app secrets in development in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-3.1&tabs=linux)

### Rider
* Navigate to **Preferences -> Plugins** and Install .NET Core User Secrets
* You can now right click on the a project (ex: Api), go to 'tools' and 'Open project user secrets'

## User Secrets - Certificates
Once you have your user secrets files setup, you'll need to generate 3 of your own certificates for use in local development.

### Generate Certificates
1. Within a terminal, navigate to ~/Desktop
2. Run the following command to create an Identity Server (Dev) certificate + key (separate)
```bash
openssl req -x509 -newkey rsa:4096 -sha256 -nodes -keyout identity_server_dev.key -out identity_server_dev.crt -subj "/CN=Bitwarden Identity Server Dev" -days 3650
```
3. Run the following command to create an Identity Server (Dev) certificate + key pfx file based on the previously created certificate + key
4. You will be prompted to enter a password - remember this because you’ll need it for your keychain
```bash
openssl pkcs12 -export -out identity_server_dev.pfx -inkey identity_server_dev.key -in identity_server_dev.crt -certfile identity_server_dev.crt
```
5. Run the following command to create a Data Protection (Dev) certificate + key (separate)
```bash
openssl req -x509 -newkey rsa:4096 -sha256 -nodes -keyout data_protection_dev.key -out data_protection_dev.crt -subj "/CN=Bitwarden Data Protection Dev" -days 3650
```
6. Once created, do the same process for a Data Protection (Dev) certificate + key pfx file
7. Again, create a password so you can save the files in your keychain
```bash
openssl pkcs12 -export -out data_protection_dev.pfx -inkey data_protection_dev.key -in data_protection_dev.crt -certfile data_protection_dev.crt
```
8. Drag’n’Drop the Bitwarden License (Dev) certificate on your Desktop
   1. The password is located within a shared note on the Bitwarden Organization's **Developer** collection
9. Add all of the generated pfx files to your login keychain by double-clicking on the files
   1. You’ll need to enter the respective generated password for each
10. Update the Trust options for each certificate to `always trust` - don’t worry, this is secure…. :)
11. Get the SHA 1 thumbprint for the Identity and Data Protection certificates and them to your Api User Secrets file
12. Copy + Pasta the entire file into the Identity secrets
    1. Access the Identity user secrets the same way Api user

## Running and Debugging
Launching the entire bitwarden/server solution for use with the bitwarden/web and other client projects.

### Prerequisites
* Docker MSSQL instance running (and accessible localhost)
* An ADS connection to the `vault_dev` database is running
* [Node.js](https://nodejs.org/en/) is installed with updated PATH variables for launch
* User secrets are configured, password updated to MSSQL database

### Visual Studio for macOS
You can right click on each project, **Identity** and then **Api**, in order, and click _Start Debugging Project_.

You can also, alternatively if you only need them running locally w/o debugging, open a terminal and navigate to each respective .csproj location and type,

```bash
dotnet run
```

NOTE: when doing this the port number on the URL may be different and you'll need to update any client configuration(s) and/or user secrets accordingly (typically the Api user secrets for the Identity URL).

### Rider
* From within Rider, launch both the Api project and the Identity project
    * This is done by hitting the play button for each project separately

### Notes
* Don’t be alarmed when the default localhost:port for both projects opens and it shows a 404 error
    * Test the Api deployment: http://localhost:5000/alive
    * Test the Identity deployment: http://localhost:33657/.well-known/openid-configuration
    * You should not see any errors but rather responses on the webpage(s)

**Comment by DavidSSL** [comment]
@cscharf I've tried to follow the instructions but I was unable to go further at the point where I had to double click on the .pfx file because on my Linux system this just opened up application options when I guess it was supposed to be added to the certificate manager.

Since these are not 100% familiar concepts to me and the fact that I won't have time for the next couple of months, I will bow out for now.

**Comment by echen805** [comment]
@AqeelAT are you actively working on this? If not, I can take a crack at it.

Wanted to check in to make sure I'm not stepping on anyone's toes.

**Comment by AqeelAT** [comment]
@echen805 I'm not. Feel free to do it.

**Comment by echen805** [comment]
Hi @cscharf, I have setup my local development server and was in the process of replicating the issue when I realized that organizations is a premium feature. Is there a development license I can use? 

I think this is a good first issue for me to try to work on this repo so if there isn't, I don't mind just purchasing a premium license. But I figured I'd ask first.

**Comment by cscharf** [comment]
Hi @echen805 , you can run local w/o using "self-hosted" if you can supply properly formatted connection strings for various cloud services, which is the primary hangup there. Here's a sample secrets JSON file that should get you what you need to run locally and use the "free" account + free org(s) without having to have access to billing services/APIs or cloud infrastructure as long as your SQL connection string is all set. Unless you do actually set up S3 or Azure Table storage/queues account or run locally using emulators in Docker, etc. however some features won't work (like file storage, notifications, etc.) which likely fine for this issue.

Also, see the article, "[Use the Azure Storage Emulator for development and testing](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator)", for how I use a local emulator for most of the storage operations when emulating "cloud".

For this secrets file, don't forget to replace the `<thumbprint goes here>` with the appropriate certificate thumbprints you've generated, as well as the `globalSettings:sqlServer:connectionString` value with the appropriate user + password values (and double check the database name).

Let me know if you run into any issues, I've not had a chance to test this configuration so there may need to be a tweak or 2.

[secrets.json.txt](https://github.com/bitwarden/server/files/5409129/secrets.json.txt)

**Comment by echen805** [comment]
Awesome, thanks so much! I'll try it out this week!

**Comment by andrenogj** [comment]
Excuse me @echen805, are you still working on this? If not, I would like to try it :)

**Comment by eliykat** [comment]
For @andrenogj and anyone else who picks up this issue: we now have really detailed instructions on how to set up your local dev environment in `SETUP.md` in this repo. You should follow `SETUP.md`, not Chad's instructions above. If you need any assistance, you can post in our [Gitter chat](https://gitter.im/bitwarden/Lobby).

**Comment by echen805** [comment]
@andrenogj Feel free to take it over, switched computers since then and haven't had a chance to setup local dev. Thanks for asking!

**Comment by andrenogj** [comment]
Thanks @echen805! I'll give it a try

**Comment by subodhmk** [comment]
@alexacallmebaka kindly assign to me 
will try

**Comment by eliykat** [comment]
@subodhmk  I haven't seen any progress on this in a while, so you're welcome to try. I expect it will require a new SQL query, see the discussion here: https://github.com/bitwarden/server/pull/1455.
