### ISSUE TITLE
Export csv does not work for type 'card'.

### ISSUE THREAD

**Issue by nemonein** [bitwarden/server#854]
**Server** : on premise, Ubuntu 18.04 with Docker, current latest version.
**Client** : google Chrome browser on KDE Neon(KDE 18.04 based)

Hello.
I've created a few records using Card type in Bitwarden, and I tried to export it through CSV.
However, there are no card records in the CSV file, type 'login' and 'secureNote' only.

But json format, it includes everything.

**Comment by kspearrin** [comment]
This is currently the expected functionality. CSV only includes logins and notes.

**Comment by cscharf** [comment]
Thanks @nemonein , since this expected functionality and we use GitHub issues as a place to track bugs and other development related issues I'll point out that the [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
