### ISSUE TITLE
Add global equivalent domains [airfrance.com, klm.com, flyingblue.com]

### ISSUE THREAD

**Issue by sebthom** [bitwarden/server#855]
Please add [airfrance.com](https://airfrance.com), [klm.com](https://klm.com), [flyingblue.com](https://flyingblue.com) as equivalent domains so we can use the Flying Blue account to login.

**Comment by clayadams5226** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
