### ISSUE TITLE
admin console is not working 

### ISSUE THREAD

**Issue by sreekanththummala** [bitwarden/server#887]
Hi Team,

I have installed a self hosted bitwarden on centos 7 and when I tried to access the admin console using https://<FQDN>/admin it takes me to a page to enter the emailID and when I provide the details and proceed, it takes me to the blank page as shown below.
Please check and do the needfull.

And the email verification doesnt work as well. I tried it with open smtp and sendgrid, nothing works.

![image](https://user-images.githubusercontent.com/34542649/91152735-a46d7400-e6bf-11ea-84ba-3afa113d7526.png)

**Comment by cscharf** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
