### ISSUE TITLE
Misleading 'Additional Storage' size on the admin page

### ISSUE THREAD

**Issue by mitch8b** [bitwarden/server#909]
Could this be changed to show the actual amount of storage physically available for the user, instead of defaulting to showing the theoretical(?) 10tb
[found here](https://github.com/bitwarden/server/blob/59f8467f7c0fa292e1f894146f066d92c4001a89/src/Core/Services/Implementations/UserService.cs#L876)

I know little about coding so if there's a reason it is like this please share:)

Thanks

**Comment by cscharf** [comment]
The short answer is, yes, it presumably _could_ be.

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

Please [sign up on our forums](https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. Thanks!
