### ISSUE TITLE
SMTP- Email not sending

### ISSUE THREAD

**Issue by mrventerj** [bitwarden/server#944]
I have read a few users SMTP issues and tried to implement them with no success.

I used Swaks to do a smtp test. (using Office 365 SMTP config)
 1-  "apt-get install swaks"   --- 2- "swaks --to user@example.com"    

Received the email- so it definitely used the SMTP config in my bitwarden dir.

So why would I not receive emails from bitwarden gui?  Why is the email setup such an issue

**Comment by clayadams5226** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
