### ISSUE TITLE
SSO - Azure AD apps, Requested query string is too long

### ISSUE THREAD

**Issue by Ikallin** [bitwarden/server#953]
Hi all,

We have Bitwarden v1.37 with SSO feature.
After configuring that feature and test it with an Azure AD app, it sends us the error ; 

AADSTS90015: Requested query string is too long.

After some investigation, we found that it seems to be the "state" parameter in the request. It adds a lot of characters and if we delete that "state", we have a fine response looking good. We think that it is the parameter causing the error.

Does anyone have tried to do SSO with Azure AD apps ? 

Have a great day !

**Comment by addisonbeck** [comment]
Are you using OpenId Connect with Azure, or SAML? 

We're aware of this issue for OpenId Connect (and you're right, it absolutely is because of state) - but have found everything works as expected when using a SAML configuration. That might be a good workaround for you while we troubleshoot OIDC.

**Comment by Ikallin** [comment]
Hi addisonbeck,

We are using OIDC, thanks for those precisions, it helps a lot.
We will try to use SAML instead while you are troubleshooting OIDC and look about any news in future updates !

Good luck with that

**Comment by cscharf** [comment]
@Ikallin ,

We have a PR ready with a fix for this and should be able to get it verified and released soon. If you need to get SAML working in the meantime please try using HTTP POST method instead of Redirect for your SAML binding, that should get all the noise out of the URL for you. (this is the similar fix/approach we're taking with OIDC btw).

**Comment by Ikallin** [comment]
Thanks for that reactivity !

We are going to try this ASAP
