### ISSUE TITLE
Feature Request IBAN

### ISSUE THREAD

**Issue by Y0ngg4n** [bitwarden/server#959]
I miss the option to save (Online) Banking data, such things like IBAN and BIC. This Option would be great espacially for auto filling of forms. Currently i save them in custom fields but this is not very usefull when it comes to auto filling forms.
Maybe add this option to cards. Would be nice. 👍

**Comment by Greenderella** [comment]
We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com/) has a section for submitting, voting for, and discussing product[ feature requests](https://community.bitwarden.com/c/feature-requests/5) like this one.

Please [sign up on our forums](https://community.bitwarden.com/) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

**Comment by Y0ngg4n** [comment]
@Greenderella oh ok thank you
