### ISSUE TITLE
Installing Bitwarden with Apache2 installed. 

### ISSUE THREAD

**Issue by ArtMason** [bitwarden/server#985]
This is an information gathering question. Back a few months ago I installed Bitwarden on a Debian 10 server (linode) with no issues what so ever.

Now I wish to move the install to an Ubuntu 18.04 server with serveral other websites running on it using Apache2. When I attempt he install I get the error message below.

docker.io/certbot/certbot:latest
docker: Error response from daemon: driver failed programming external connectivity on endpoint certbot (1da6959bb851326c9212d1b0c966c048ebf7ce53b3111f4c4aa9413c1523a416): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use.

Yes I have pointed the DNS server towards the new site. It appears to me I have a port conflict with apache?  Any help would be greatly appreciated!!

Thank you!

Art

**Comment by SergeantConfused** [comment]
Hi Art,

Yes, this is a port conflict. In order to use Let's Encrypt you have to use port 80 and 443. 

Please stop apache temporarily until the certificate has been created, and then start apache again afterwards. Please note that you'll need to do this every time you renew the certificate.

It's recommended to not run Bitwarden on the same server as apache if you are going to use Let's Encrypt. If you choose not to use Let's Encrypt, you can change the ports Bitwarden uses in the config.yml and run `./bitwarden.sh rebuild`. Then you'll need to set the custom ports on all URIs in the global.override.env file.

If you have any further questions, please feel free to get in touch with us here: https://bitwarden.com/contact/


All the best,

**Comment by ArtMason** [comment]
Awesome! Thank you very much!
